// GÉNÉRÉ par scripts/feasibility.mjs — ne pas éditer. 25 seeds par combinaison.
// 112 combinaisons déclarées, 25 jamais servies.
import type { Discipline, Intention, SkeletonFormat } from '../types';

export interface FeasibilityRow {
  id: string;
  discipline: Discipline;
  format: SkeletonFormat;
  budget_min: number;
  intention: Intention;
  /** au moins un tirage sur 25 aboutit, ce squelette seul autorisé */
  feasible: boolean;
}

export const FEASIBILITY: readonly FeasibilityRow[] = [
  { id: 'couplet_for_time_21_15_9', discipline: 'functional', format: 'for_time', budget_min: 8, intention: 'mixed', feasible: true },
  { id: 'couplet_for_time_21_15_9', discipline: 'functional', format: 'for_time', budget_min: 8, intention: 'gym', feasible: true },
  { id: 'couplet_for_time_21_15_9', discipline: 'functional', format: 'for_time', budget_min: 8, intention: 'force', feasible: false },
  { id: 'couplet_for_time_21_15_9', discipline: 'functional', format: 'for_time', budget_min: 12, intention: 'mixed', feasible: false },
  { id: 'couplet_for_time_21_15_9', discipline: 'functional', format: 'for_time', budget_min: 12, intention: 'gym', feasible: false },
  { id: 'couplet_for_time_21_15_9', discipline: 'functional', format: 'for_time', budget_min: 12, intention: 'force', feasible: false },
  { id: 'couplet_amrap_short', discipline: 'functional', format: 'amrap', budget_min: 8, intention: 'mixed', feasible: true },
  { id: 'couplet_amrap_short', discipline: 'functional', format: 'amrap', budget_min: 8, intention: 'cardio', feasible: true },
  { id: 'couplet_amrap_short', discipline: 'functional', format: 'amrap', budget_min: 8, intention: 'gym', feasible: true },
  { id: 'couplet_amrap_short', discipline: 'functional', format: 'amrap', budget_min: 12, intention: 'mixed', feasible: true },
  { id: 'couplet_amrap_short', discipline: 'functional', format: 'amrap', budget_min: 12, intention: 'cardio', feasible: true },
  { id: 'couplet_amrap_short', discipline: 'functional', format: 'amrap', budget_min: 12, intention: 'gym', feasible: true },
  { id: 'triplet_amrap_mid', discipline: 'functional', format: 'amrap', budget_min: 12, intention: 'mixed', feasible: true },
  { id: 'triplet_amrap_mid', discipline: 'functional', format: 'amrap', budget_min: 12, intention: 'cardio', feasible: true },
  { id: 'triplet_amrap_mid', discipline: 'functional', format: 'amrap', budget_min: 15, intention: 'mixed', feasible: true },
  { id: 'triplet_amrap_mid', discipline: 'functional', format: 'amrap', budget_min: 15, intention: 'cardio', feasible: true },
  { id: 'triplet_amrap_mid', discipline: 'functional', format: 'amrap', budget_min: 20, intention: 'mixed', feasible: true },
  { id: 'triplet_amrap_mid', discipline: 'functional', format: 'amrap', budget_min: 20, intention: 'cardio', feasible: true },
  { id: 'triplet_rounds_for_time', discipline: 'functional', format: 'rounds_for_time', budget_min: 12, intention: 'mixed', feasible: true },
  { id: 'triplet_rounds_for_time', discipline: 'functional', format: 'rounds_for_time', budget_min: 12, intention: 'force', feasible: true },
  { id: 'triplet_rounds_for_time', discipline: 'functional', format: 'rounds_for_time', budget_min: 15, intention: 'mixed', feasible: true },
  { id: 'triplet_rounds_for_time', discipline: 'functional', format: 'rounds_for_time', budget_min: 15, intention: 'force', feasible: true },
  { id: 'triplet_rounds_for_time', discipline: 'functional', format: 'rounds_for_time', budget_min: 20, intention: 'mixed', feasible: true },
  { id: 'triplet_rounds_for_time', discipline: 'functional', format: 'rounds_for_time', budget_min: 20, intention: 'force', feasible: true },
  { id: 'chipper_descending', discipline: 'functional', format: 'chipper', budget_min: 15, intention: 'mixed', feasible: true },
  { id: 'chipper_descending', discipline: 'functional', format: 'chipper', budget_min: 15, intention: 'cardio', feasible: false },
  { id: 'chipper_descending', discipline: 'functional', format: 'chipper', budget_min: 20, intention: 'mixed', feasible: false },
  { id: 'chipper_descending', discipline: 'functional', format: 'chipper', budget_min: 20, intention: 'cardio', feasible: false },
  { id: 'chipper_stations_erg', discipline: 'functional', format: 'chipper', budget_min: 20, intention: 'mixed', feasible: true },
  { id: 'chipper_stations_erg', discipline: 'functional', format: 'chipper', budget_min: 20, intention: 'cardio', feasible: true },
  { id: 'chipper_stations_erg', discipline: 'functional', format: 'chipper', budget_min: 30, intention: 'mixed', feasible: false },
  { id: 'chipper_stations_erg', discipline: 'functional', format: 'chipper', budget_min: 30, intention: 'cardio', feasible: false },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 12, intention: 'mixed', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 12, intention: 'gym', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 12, intention: 'force', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 15, intention: 'mixed', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 15, intention: 'gym', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 15, intention: 'force', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 20, intention: 'mixed', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 20, intention: 'gym', feasible: true },
  { id: 'emom_alternating', discipline: 'functional', format: 'emom', budget_min: 20, intention: 'force', feasible: true },
  { id: 'interval_work_rest', discipline: 'functional', format: 'interval', budget_min: 15, intention: 'mixed', feasible: true },
  { id: 'interval_work_rest', discipline: 'functional', format: 'interval', budget_min: 15, intention: 'cardio', feasible: true },
  { id: 'interval_work_rest', discipline: 'functional', format: 'interval', budget_min: 15, intention: 'force', feasible: true },
  { id: 'interval_work_rest', discipline: 'functional', format: 'interval', budget_min: 20, intention: 'mixed', feasible: true },
  { id: 'interval_work_rest', discipline: 'functional', format: 'interval', budget_min: 20, intention: 'cardio', feasible: true },
  { id: 'interval_work_rest', discipline: 'functional', format: 'interval', budget_min: 20, intention: 'force', feasible: true },
  { id: 'ladder_ascending', discipline: 'functional', format: 'ladder', budget_min: 10, intention: 'mixed', feasible: true },
  { id: 'ladder_ascending', discipline: 'functional', format: 'ladder', budget_min: 10, intention: 'gym', feasible: true },
  { id: 'ladder_ascending', discipline: 'functional', format: 'ladder', budget_min: 15, intention: 'mixed', feasible: false },
  { id: 'ladder_ascending', discipline: 'functional', format: 'ladder', budget_min: 15, intention: 'gym', feasible: false },
  { id: 'death_by', discipline: 'functional', format: 'death_by', budget_min: 10, intention: 'mixed', feasible: true },
  { id: 'death_by', discipline: 'functional', format: 'death_by', budget_min: 10, intention: 'force', feasible: true },
  { id: 'death_by', discipline: 'functional', format: 'death_by', budget_min: 15, intention: 'mixed', feasible: true },
  { id: 'death_by', discipline: 'functional', format: 'death_by', budget_min: 15, intention: 'force', feasible: true },
  { id: 'tabata_pair', discipline: 'functional', format: 'tabata', budget_min: 8, intention: 'cardio', feasible: true },
  { id: 'tabata_pair', discipline: 'functional', format: 'tabata', budget_min: 8, intention: 'gym', feasible: false },
  { id: 'tabata_pair', discipline: 'functional', format: 'tabata', budget_min: 10, intention: 'cardio', feasible: true },
  { id: 'tabata_pair', discipline: 'functional', format: 'tabata', budget_min: 10, intention: 'gym', feasible: false },
  { id: 'heavy_couplet', discipline: 'functional', format: 'rounds_for_time', budget_min: 10, intention: 'force', feasible: true },
  { id: 'heavy_couplet', discipline: 'functional', format: 'rounds_for_time', budget_min: 15, intention: 'force', feasible: true },
  { id: 'engine_long_amrap', discipline: 'functional', format: 'amrap', budget_min: 20, intention: 'cardio', feasible: true },
  { id: 'engine_long_amrap', discipline: 'functional', format: 'amrap', budget_min: 30, intention: 'cardio', feasible: true },
  { id: 'gym_density', discipline: 'functional', format: 'emom', budget_min: 10, intention: 'gym', feasible: true },
  { id: 'gym_density', discipline: 'functional', format: 'emom', budget_min: 15, intention: 'gym', feasible: true },
  { id: 'stations_rotation', discipline: 'functional', format: 'stations', budget_min: 20, intention: 'mixed', feasible: true },
  { id: 'stations_rotation', discipline: 'functional', format: 'stations', budget_min: 20, intention: 'cardio', feasible: true },
  { id: 'stations_rotation', discipline: 'functional', format: 'stations', budget_min: 30, intention: 'mixed', feasible: true },
  { id: 'stations_rotation', discipline: 'functional', format: 'stations', budget_min: 30, intention: 'cardio', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'interval', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'engine', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'run', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 30, intention: 'interval', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 30, intention: 'engine', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 30, intention: 'run', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 45, intention: 'interval', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 45, intention: 'engine', feasible: true },
  { id: 'run_into_station', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 45, intention: 'run', feasible: true },
  { id: 'stations_interval', discipline: 'hybrid', format: 'stations', budget_min: 20, intention: 'interval', feasible: true },
  { id: 'stations_interval', discipline: 'hybrid', format: 'stations', budget_min: 30, intention: 'interval', feasible: true },
  { id: 'amrap_distances', discipline: 'hybrid', format: 'amrap', budget_min: 15, intention: 'interval', feasible: true },
  { id: 'amrap_distances', discipline: 'hybrid', format: 'amrap', budget_min: 15, intention: 'engine', feasible: true },
  { id: 'amrap_distances', discipline: 'hybrid', format: 'amrap', budget_min: 20, intention: 'interval', feasible: true },
  { id: 'amrap_distances', discipline: 'hybrid', format: 'amrap', budget_min: 20, intention: 'engine', feasible: true },
  { id: 'erg_pyramid', discipline: 'hybrid', format: 'for_time', budget_min: 20, intention: 'engine', feasible: false },
  { id: 'erg_pyramid', discipline: 'hybrid', format: 'for_time', budget_min: 20, intention: 'aerobic', feasible: false },
  { id: 'erg_pyramid', discipline: 'hybrid', format: 'for_time', budget_min: 30, intention: 'engine', feasible: false },
  { id: 'erg_pyramid', discipline: 'hybrid', format: 'for_time', budget_min: 30, intention: 'aerobic', feasible: false },
  { id: 'sled_repeats', discipline: 'hybrid', format: 'interval', budget_min: 15, intention: 'force', feasible: false },
  { id: 'sled_repeats', discipline: 'hybrid', format: 'interval', budget_min: 15, intention: 'interval', feasible: false },
  { id: 'sled_repeats', discipline: 'hybrid', format: 'interval', budget_min: 20, intention: 'force', feasible: false },
  { id: 'sled_repeats', discipline: 'hybrid', format: 'interval', budget_min: 20, intention: 'interval', feasible: false },
  { id: 'compromised_run', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'interval', feasible: true },
  { id: 'compromised_run', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'run', feasible: true },
  { id: 'compromised_run', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 30, intention: 'interval', feasible: true },
  { id: 'compromised_run', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 30, intention: 'run', feasible: true },
  { id: 'half_sim', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 15, intention: 'interval', feasible: false },
  { id: 'half_sim', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'interval', feasible: true },
  { id: 'engine_continuous', discipline: 'hybrid', format: 'continuous', budget_min: 20, intention: 'aerobic', feasible: true },
  { id: 'engine_continuous', discipline: 'hybrid', format: 'continuous', budget_min: 30, intention: 'aerobic', feasible: true },
  { id: 'engine_continuous', discipline: 'hybrid', format: 'continuous', budget_min: 35, intention: 'aerobic', feasible: true },
  { id: 'engine_continuous', discipline: 'hybrid', format: 'continuous', budget_min: 40, intention: 'aerobic', feasible: true },
  { id: 'engine_continuous', discipline: 'hybrid', format: 'continuous', budget_min: 45, intention: 'aerobic', feasible: true },
  { id: 'core_carry_finisher', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 10, intention: 'core', feasible: true },
  { id: 'core_carry_finisher', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 15, intention: 'core', feasible: true },
  { id: 'core_carry_finisher', discipline: 'hybrid', format: 'rounds_for_time', budget_min: 20, intention: 'core', feasible: true },
  { id: 'run_intervals', discipline: 'hybrid', format: 'interval', budget_min: 10, intention: 'run', feasible: true },
  { id: 'run_intervals', discipline: 'hybrid', format: 'interval', budget_min: 15, intention: 'run', feasible: true },
  { id: 'run_intervals', discipline: 'hybrid', format: 'interval', budget_min: 20, intention: 'run', feasible: true },
  { id: 'engine_negative_split', discipline: 'hybrid', format: 'continuous', budget_min: 30, intention: 'aerobic', feasible: false },
  { id: 'engine_negative_split', discipline: 'hybrid', format: 'continuous', budget_min: 35, intention: 'aerobic', feasible: false },
  { id: 'engine_negative_split', discipline: 'hybrid', format: 'continuous', budget_min: 40, intention: 'aerobic', feasible: false },
];
