-- ═════════════════════════════════════════════════════════════════════════════
-- Catalogue « sans matériel » : 55 exercices de plus.
--
-- Appliquée en prod : NON.
--
-- Additif et rejouable (`ON CONFLICT (id) DO NOTHING`) : aucune ligne existante
-- n'est modifiée, aucune supprimée.
--
-- Constat des tests réels sur 1.0.54 : en Musculation « Sans matériel », Pike
-- Push-Ups et Wall Triceps Extension revenaient sur presque tous les tirages.
-- La règle de priorité n'y était pour rien — le catalogue n'avait littéralement
-- pas d'autre choix. Mesuré en prod le 17/09/2026, par muscle principal :
--
--   dos, biceps, trapèzes, avant-bras, coiffe, épaules ant. / post. :  0
--   ischios, lombaires, mollets                                     :  1
--   épaules                                                         :  2
--   triceps                                                         :  2
--
-- Sept muscles sans aucune option : un athlète qui visait le dos ne pouvait
-- recevoir qu'une séance hors sujet. Après ce lot, aucun muscle travaillé par
-- le générateur n'est à moins de deux.
--
-- Poids metcon à zéro : ces exercices ne sont pas tirables en WOD, seulement en
-- Musculation. L'élastique compte comme « sans matériel » (décision produit) :
-- ce n'est pas du matériel de salle.
--
-- Écrits à la main, et non régénérés depuis `catalogue-musculation-v1.csv` :
-- `scripts/import-catalog.cjs` réécrit `20261214`, déjà appliquée en prod, même
-- quand le CSV n'a pas changé. Non-reproductibilité signalée dans l'issue.
-- ═════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.movement_catalog
  ADD COLUMN IF NOT EXISTS priority_bodyweight smallint
  CHECK (priority_bodyweight IS NULL OR priority_bodyweight BETWEEN 1 AND 5);

COMMENT ON COLUMN public.movement_catalog.priority_bodyweight IS
  'Priorité propre au mode « Sans matériel » ; NULL = pas d''ordre spécifique, on retombe sur priority. Deux modes, deux ordres : une pompe classique reste devant une pompe déclinée en salle, mais sans matériel c''est la variété qui prime.';

INSERT INTO public.movement_catalog
  (id, name, family, pattern, modality, grip, shoulder_load, unit_default, units_allowed,
   load_unit, weight_functional, weight_hybrid, equipment, badge_key, active, version, notes,
   discipline_muscu, muscle_primary, muscle_secondary, compound, unilateral, level_min,
   load_mode, rm_reference, rm_factor, seconds_per_rep, setup_s,
   objectives, rep_ranges_muscu, weight_bodyweight, weight_box, weight_gym, muscu_unit,
   priority, priority_bodyweight, movement_group)
VALUES
  ('pike_push_up_elevated', 'Pike Push-Ups surélevées', 'bodyweight', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'pieds surélevés : plus vertical, plus proche du HSPU', true, 'epaules', ARRAY['triceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[6,12],"endurance":[12,20]}'::jsonb, 7, 7, 7, 'reps', 2, 1, 'press_v'),
  ('hindu_push_up', 'Pompes Hindu', 'bodyweight', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'epaules', ARRAY['pecs', 'triceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,25]}'::jsonb, 6, 6, 6, 'reps', 3, 2, 'press_v'),
  ('handstand_hold', 'Handstand Hold', 'bodyweight', ARRAY['push_v']::text[], 'G', 'none', 'high', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'tenue, unité en secondes', true, 'epaules', ARRAY['tronc']::text[], false, false, 'inter', 'bodyweight', NULL, NULL, 1, 20, ARRAY['endurance']::text[], '{"endurance":[20,60]}'::jsonb, 5, 6, 6, 's', 4, 3, 'press_v'),
  ('prone_ytw', 'Prone Y-T-W', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'au sol, sans charge : trapèzes moyens et bas', true, 'trapezes', ARRAY['epaules_post', 'dos']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 1, 'raise'),
  ('reverse_snow_angel', 'Reverse Snow Angels', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'epaules_post', ARRAY['trapezes']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[20,30]}'::jsonb, 8, 6, 6, 'reps', 1, 1, 'raise'),
  ('diamond_push_up_decline', 'Pompes diamant déclinées', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'triceps', ARRAY['pecs']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 1, 'press_h'),
  ('floor_triceps_extension', 'Extensions triceps au sol', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'skull crusher au poids du corps, genoux ou pieds', true, 'triceps', ARRAY['epaules_ant']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[12,20]}'::jsonb, 7, 6, 6, 'reps', 2, 1, 'triceps_ext'),
  ('close_push_up_box', 'Pompes serrées sur box', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'triceps', ARRAY['pecs']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[20,30]}'::jsonb, 6, 8, 8, 'reps', 3, 2, 'press_h'),
  ('archer_push_up', 'Pompes archer', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'une main tendue : charge décalée sur un côté', true, 'pecs', ARRAY['triceps', 'epaules_ant']::text[], true, true, 'avance', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[5,10],"force":[3,6]}'::jsonb, 7, 7, 7, 'reps', 3, 1, 'press_h'),
  ('decline_push_up_wall', 'Pompes déclinées pieds au mur', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'pecs', ARRAY['epaules_ant', 'triceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 7, 6, 6, 'reps', 4, 2, 'press_h'),
  ('weighted_bag_push_up', 'Pompes lestées (sac)', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'sac à dos chargé : progression quand les pompes deviennent faciles', true, 'pecs', ARRAY['triceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[4,6]}'::jsonb, 6, 7, 7, 'reps', 5, 3, 'press_h'),
  ('inverted_row_table', 'Rowing inversé sous table', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'table, barre basse ou anneaux : le tirage horizontal sans matériel', true, 'dos', ARRAY['biceps', 'trapezes']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,15],"endurance":[15,25]}'::jsonb, 9, 8, 8, 'reps', 1, 1, 'row'),
  ('superman_pull', 'Superman Pull', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'dos', ARRAY['lombaires', 'trapezes']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[20,30]}'::jsonb, 8, 6, 6, 'reps', 2, 3, 'row'),
  ('scapular_pull_up', 'Scapular Pull-Ups', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['pull_up_bar']::text[], NULL, true, 1, 'barre fixe : réservé au mode Box', true, 'dos', ARRAY['trapezes']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[12,20]}'::jsonb, 0, 8, 8, 'reps', 3, 3, 'pull_v'),
  ('band_pull_apart', 'Écartés à l''élastique', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique : admis en sans matériel', true, 'epaules_post', ARRAY['trapezes']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[12,20],"endurance":[20,30]}'::jsonb, 7, 7, 7, 'reps', 2, 2, 'raise'),
  ('chin_up_supine', 'Tractions supination', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['pull_up_bar']::text[], NULL, true, 1, 'barre fixe : réservé au mode Box', true, 'biceps', ARRAY['dos']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[5,10],"force":[3,6]}'::jsonb, 0, 9, 9, 'reps', 1, 1, 'pull_v'),
  ('band_biceps_curl', 'Curls à l''élastique', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique : admis en sans matériel', true, 'biceps', ARRAY['avant_bras']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 2, 1, 'curl'),
  ('towel_curl_isometric', 'Curls isométriques à la serviette', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'auto-résistance : une main freine l''autre', true, 'biceps', ARRAY['avant_bras']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[12,20]}'::jsonb, 6, 5, 5, 'reps', 3, 2, 'curl'),
  ('bar_hang_shrug', 'Shrugs suspendus à la barre', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['pull_up_bar']::text[], NULL, true, 1, 'barre fixe : réservé au mode Box', true, 'trapezes', ARRAY['dos']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,15],"endurance":[15,25]}'::jsonb, 0, 8, 8, 'reps', 2, 1, 'shrug'),
  ('scapular_push_up', 'Scapular Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'trapèzes inférieurs et dentelé, en planche', true, 'trapezes', ARRAY['epaules_ant']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,20],"endurance":[20,30]}'::jsonb, 7, 6, 6, 'reps', 3, 2, 'shrug'),
  ('dead_hang', 'Suspension passive', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'medium', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY['pull_up_bar']::text[], NULL, true, 1, 'barre fixe : réservé au mode Box, unité en secondes', true, 'avant_bras', ARRAY['dos']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 15, ARRAY['endurance']::text[], '{"endurance":[20,60]}'::jsonb, 0, 9, 9, 's', 1, 1, 'carry'),
  ('fingertip_push_up', 'Pompes sur les doigts', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'doigts en appui : poignets et fléchisseurs', true, 'avant_bras', ARRAY['pecs', 'triceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[6,12],"endurance":[10,20]}'::jsonb, 8, 7, 7, 'reps', 2, 1, 'press_h'),
  ('bodyweight_wrist_curl', 'Flexions de poignet au poids du corps', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'à genoux, mains au sol', true, 'avant_bras', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[12,20],"endurance":[20,30]}'::jsonb, 7, 6, 6, 'reps', 3, 2, 'carry'),
  ('band_external_rotation', 'Rotations externes à l''élastique', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique, coude au corps : admis en sans matériel', true, 'coiffe', ARRAY['epaules_post']::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[12,20],"endurance":[20,30]}'::jsonb, 8, 7, 7, 'reps', 1, 1, 'raise'),
  ('band_face_pull', 'Face Pull à l''élastique', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique à hauteur de visage', true, 'coiffe', ARRAY['epaules_post', 'trapezes']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[12,20],"endurance":[20,30]}'::jsonb, 7, 7, 7, 'reps', 2, 2, 'raise'),
  ('prone_external_rotation', 'Rotations externes à plat ventre', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'sans charge, amplitude lente', true, 'coiffe', ARRAY['epaules_post']::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 4, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 7, 6, 6, 'reps', 3, 3, 'raise'),
  ('band_lat_pulldown_kneeling', 'Tirage vertical élastique à genoux', 'bodyweight', ARRAY['pull_v']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique ancré haut, à genoux : amplitude complète sans barre', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 1, 'pull_v'),
  ('band_single_arm_pulldown', 'Tirage élastique un bras', 'bodyweight', ARRAY['pull_v']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'un bras à la fois : corrige les asymétries', true, 'dos', ARRAY['biceps']::text[], true, true, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,14],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 2, 3, 'pull_v'),
  ('band_bent_over_row', 'Rowing élastique buste penché', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique sous les pieds, dos plat', true, 'dos', ARRAY['biceps', 'trapezes']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 2, 3, 'row'),
  ('inverted_row_feet_elevated', 'Rowing inversé pieds surélevés', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'pieds sur une chaise : le tirage horizontal le plus chargeant sans matériel', true, 'dos', ARRAY['biceps', 'trapezes']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[6,12],"force":[5,8]}'::jsonb, 8, 8, 8, 'reps', 1, 2, 'row'),
  ('towel_row_post', 'Rowing serviette autour d''un poteau', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'serviette autour d''un montant : partout, sans rien', true, 'dos', ARRAY['biceps', 'avant_bras']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 6, 6, 'reps', 3, 3, 'row'),
  ('band_lat_pulldown', 'Tirage vertical à l''élastique', 'bodyweight', ARRAY['pull_v']::text[], 'G', 'none', 'medium', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique ancré en hauteur : le tirage vertical sans barre', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 2, 'pull_v'),
  ('band_face_pull_high', 'Face Pull élastique haut', 'bodyweight', ARRAY['pull_v']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique en hauteur, coudes hauts', true, 'dos', ARRAY['trapezes', 'epaules_post']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[12,20],"endurance":[20,30]}'::jsonb, 7, 7, 7, 'reps', 2, 3, 'pull_v'),
  ('band_curl_supine_grip', 'Curls élastique prise supination large', 'bodyweight', ARRAY['pull_v']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique sous les pieds, coudes au corps', true, 'biceps', ARRAY['dos']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 2, 'pull_v'),
  ('band_hammer_curl', 'Curls marteau à l''élastique', 'bodyweight', ARRAY['pull_v']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'prise neutre', true, 'biceps', ARRAY['avant_bras']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 7, 7, 7, 'reps', 2, 3, 'pull_v'),
  ('chair_step_up', 'Step-up sur chaise', 'bodyweight', ARRAY['lunge']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'montée contrôlée, descente freinée', true, 'fessiers', ARRAY['quadriceps']::text[], true, true, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 9, 8, 8, 'reps', 1, 1, 'lunge'),
  ('lateral_lunge', 'Fente latérale', 'bodyweight', ARRAY['lunge']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'fessiers', ARRAY['quadriceps', 'ischios']::text[], true, true, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 2, 2, 'lunge'),
  ('bird_dog_hold', 'Bird Dog tenu', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'bras et jambe opposés, bassin fixe', true, 'lombaires', ARRAY['fessiers', 'tronc']::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,14],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 1, 'core_anti'),
  ('pallof_press_band', 'Pallof Press à l''élastique', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'élastique latéral : anti-rotation', true, 'obliques', ARRAY['tronc']::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 1, 'core_anti'),
  ('prone_ytw_hold', 'Prone Y-T-W tenu', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'chaque position tenue 3 s', true, 'trapezes', ARRAY['epaules_post']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 4, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,25]}'::jsonb, 7, 6, 6, 'reps', 2, 2, 'raise'),
  ('band_row', 'Rowing à l''élastique', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique ancré : le tirage horizontal partout', true, 'dos', ARRAY['biceps', 'trapezes']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 2, 3, 'row'),
  ('scapular_pull_floor', 'Scapular Pull au sol', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'à plat ventre, omoplates seules : sans barre', true, 'dos', ARRAY['trapezes']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 7, 6, 6, 'reps', 4, 3, 'row'),
  ('band_overhead_triceps_extension', 'Extensions triceps élastique au-dessus de la tête', 'bodyweight', ARRAY['push_v']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'élastique derrière la nuque', true, 'triceps', ARRAY['epaules']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 2, 2, 'triceps_ext'),
  ('bulgarian_split_squat_chair', 'Fentes bulgares (pied sur chaise)', 'bodyweight', ARRAY['lunge']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'pied arrière sur une chaise : la fente la plus chargeante sans matériel', true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'inter', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[5,8]}'::jsonb, 9, 8, 8, 'reps', 2, 1, 'lunge'),
  ('reverse_lunge_slow', 'Fente arrière lente', 'bodyweight', ARRAY['lunge']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'descente contrôlée, sans charge', true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'debutant', 'bodyweight', NULL, NULL, 4, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 3, 2, 'lunge'),
  ('jump_squat', 'Squat sauté', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'quadriceps', ARRAY['fessiers', 'mollets']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,16],"endurance":[20,30]}'::jsonb, 8, 7, 7, 'reps', 2, 1, 'squat'),
  ('cossack_squat', 'Cossack Squat', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'squat latéral, jambe opposée tendue', true, 'quadriceps', ARRAY['fessiers', 'ischios']::text[], true, true, 'inter', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[6,12],"endurance":[12,20]}'::jsonb, 8, 7, 7, 'reps', 3, 2, 'squat'),
  ('shrimp_squat', 'Shrimp Squat', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'avance', 'bodyweight', NULL, NULL, 5, 10, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[4,8],"force":[3,5]}'::jsonb, 7, 6, 6, 'reps', 4, 3, 'squat'),
  ('sissy_squat', 'Sissy Squat', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'quadriceps en étirement, appui léger', true, 'quadriceps', ARRAY[]::text[], false, false, 'inter', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[12,20]}'::jsonb, 7, 6, 6, 'reps', 5, 3, 'squat'),
  ('jumping_lunge', 'Fentes sautées', 'bodyweight', ARRAY['lunge']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'quadriceps', ARRAY['fessiers', 'mollets']::text[], true, true, 'inter', 'bodyweight', NULL, NULL, 2, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,16],"endurance":[20,30]}'::jsonb, 8, 7, 7, 'reps', 5, 3, 'lunge'),
  ('single_leg_calf_raise', 'Mollets unilatéraux', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'sur une marche, amplitude complète', true, 'mollets', ARRAY[]::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[12,20],"endurance":[20,30]}'::jsonb, 9, 8, 8, 'reps', 1, 1, 'raise'),
  ('nordic_curl_assisted', 'Nordic Curl assisté', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'pieds bloqués, descente freinée', true, 'ischios', ARRAY['fessiers']::text[], true, false, 'avance', 'bodyweight', NULL, NULL, 5, 20, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[4,8],"force":[3,6]}'::jsonb, 7, 6, 6, 'reps', 2, 1, 'hinge'),
  ('weighted_dead_bug', 'Dead Bug lesté', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'sac ou bouteilles dans les mains', true, 'tronc', ARRAY['obliques']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,14],"endurance":[15,25]}'::jsonb, 7, 7, 7, 'reps', 4, 1, 'core_anti'),
  ('floor_toes_to_bar', 'Toes-to-Bar au sol', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'allongé, mains au sol au-dessus de la tête', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[20,30]}'::jsonb, 7, 6, 6, 'reps', 5, 1, 'core_flex'),
  ('side_plank_rotation', 'Side Plank avec rotation', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, NULL, true, 'obliques', ARRAY['tronc']::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,14],"endurance":[15,25]}'::jsonb, 8, 7, 7, 'reps', 1, 2, 'core_anti')
ON CONFLICT (id) DO NOTHING;

-- `priority_bodyweight` pour TOUT le catalogue sans matériel, pas seulement les
-- nouvelles lignes : le rang dense de `priority` par (muscle × geste × rôle),
-- plafonné à 3, pour que les trois meilleures options d'une forme de slot
-- concourent réellement. Même calcul que le snapshot embarqué ; rejouable.
WITH classe AS (
  SELECT id, dense_rank() OVER (
           PARTITION BY muscle_primary, movement_group, compound ORDER BY priority
         ) AS rang
    FROM public.movement_catalog
   WHERE discipline_muscu AND load_mode = 'bodyweight' AND weight_bodyweight > 0
)
UPDATE public.movement_catalog AS m
   SET priority_bodyweight = LEAST(c.rang, 3)
  FROM classe AS c
 WHERE c.id = m.id;
