-- ═════════════════════════════════════════════════════════════════════════════
-- Générateur Musculation V1 (M1) — squelettes `discipline = 'musculation'`.
--
-- FICHIER GÉNÉRÉ par packages/wod-engine/scripts/export-bank.ts depuis
-- packages/wod-engine/src/bank/muscu.ts (DDL : scripts/wod_skeletons_muscu.ddl.sql).
-- Ne pas éditer à la main : relancer le script.
--
-- Appliquée en prod : OUI (16/09/2026 19:41 UTC, dump `20260916T194119Z` dans le bucket privé `db-dumps`).
--
-- Additif et rejouable : élargit les CHECK de `wod_skeletons` (discipline
-- `musculation`, format `strength_session`) et insère les 39 squelettes
-- (13 cibles × 3 objectifs). `definition` = `MuscuSkeleton` du package ;
-- le moteur lit les lignes `active` et retombe sur le snapshot embarqué
-- (`MUSCU_SKELETONS`) hors ligne ou sur une base sans ces lignes.
-- Les lignes functional / hybrid (version 3) ne sont pas touchées.
--
-- Prérequis côté app : l'app 1.0.53 charge toutes les lignes actives sans
-- filtrer la discipline ; ne pas appliquer avant le build embarquant M1.
-- ═════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.wod_skeletons DROP CONSTRAINT IF EXISTS wod_skeletons_discipline_check;
ALTER TABLE public.wod_skeletons ADD CONSTRAINT wod_skeletons_discipline_check
  CHECK (discipline IN ('functional','hybrid','musculation'));

ALTER TABLE public.wod_skeletons DROP CONSTRAINT IF EXISTS wod_skeletons_format_check;
ALTER TABLE public.wod_skeletons ADD CONSTRAINT wod_skeletons_format_check
  CHECK (format IN ('amrap','for_time','rounds_for_time','chipper','emom','interval','ladder','death_by','tabata','stations','continuous','strength_session'));

ALTER TABLE public.wod_skeletons DROP CONSTRAINT IF EXISTS wod_skeletons_muscu_format;
ALTER TABLE public.wod_skeletons ADD CONSTRAINT wod_skeletons_muscu_format
  CHECK ((discipline = 'musculation') = (format = 'strength_session'));

ALTER TABLE public.wod_volume_caps DROP CONSTRAINT IF EXISTS wod_volume_caps_family_check;
ALTER TABLE public.wod_volume_caps ADD CONSTRAINT wod_volume_caps_family_check
  CHECK (family IS NULL OR family IN ('barbell','dumbbell','kettlebell','gym','bodyweight','erg','run','sled','carry','sandbag','wallball','jump_rope','box','machine','cable','other'));

-- ── Seed : squelettes musculation v1 (39 squelettes, généré par packages/wod-engine/scripts/export-bank.ts) ──
INSERT INTO public.wod_skeletons (id, discipline, format, definition, active, version)
VALUES
  ('push_hypertrophie', 'musculation', 'strength_session', '{"id":"push_hypertrophie","discipline":"musculation","format":"strength_session","target":"push","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"epaules"},{"role":"isolation","muscle":"pecs"},{"role":"isolation","muscle":"epaules"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"triceps","optional":true}]}'::jsonb, true, 1),
  ('push_force', 'musculation', 'strength_session', '{"id":"push_force","discipline":"musculation","format":"strength_session","target":"push","objective":"force","slots":[{"role":"main_compound","muscle":"pecs"},{"role":"main_compound","muscle":"epaules"},{"role":"secondary_compound","muscle":"triceps","ids":["close_grip_bench","close_grip_dips","machine_dips","diamond_push_up","dips"]},{"role":"isolation","muscle":"epaules_post","optional":true},{"role":"isolation","muscle":"triceps","optional":true}]}'::jsonb, true, 1),
  ('push_endurance', 'musculation', 'strength_session', '{"id":"push_endurance","discipline":"musculation","format":"strength_session","target":"push","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"epaules"},{"role":"isolation","muscle":"pecs"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"epaules","optional":true}]}'::jsonb, true, 1),
  ('pull_hypertrophie', 'musculation', 'strength_session', '{"id":"pull_hypertrophie","discipline":"musculation","format":"strength_session","target":"pull","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"dos","ids":["strict_pull_up","chin_up","wide_grip_pull_up","neutral_grip_pull_up","close_grip_pull_up","lat_pulldown","converging_pulldown","close_grip_pulldown","supinated_pulldown","one_arm_pulldown"]},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"biceps","optional":true},{"role":"isolation","muscle":"trapezes","optional":true}]}'::jsonb, true, 1),
  ('pull_force', 'musculation', 'strength_session', '{"id":"pull_force","discipline":"musculation","format":"strength_session","target":"pull","objective":"force","slots":[{"role":"main_compound","muscle":"dos"},{"role":"main_compound","muscle":"dos","ids":["strict_pull_up","chin_up","wide_grip_pull_up","neutral_grip_pull_up","close_grip_pull_up","lat_pulldown","converging_pulldown","close_grip_pulldown","supinated_pulldown","one_arm_pulldown"]},{"role":"secondary_compound","muscle":"trapezes","optional":true},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"epaules_post","optional":true}]}'::jsonb, true, 1),
  ('pull_endurance', 'musculation', 'strength_session', '{"id":"pull_endurance","discipline":"musculation","format":"strength_session","target":"pull","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"dos","ids":["strict_pull_up","chin_up","wide_grip_pull_up","neutral_grip_pull_up","close_grip_pull_up","lat_pulldown","converging_pulldown","close_grip_pulldown","supinated_pulldown","one_arm_pulldown"]},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"biceps"},{"role":"core","muscle":["tronc","lombaires"],"optional":true}]}'::jsonb, true, 1),
  ('jambes_hypertrophie', 'musculation', 'strength_session', '{"id":"jambes_hypertrophie","discipline":"musculation","format":"strength_session","target":"jambes","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"quadriceps"},{"role":"secondary_compound","muscle":"ischios"},{"role":"secondary_compound","muscle":["quadriceps","fessiers"]},{"role":"isolation","muscle":"quadriceps"},{"role":"isolation","muscle":"ischios"},{"role":"calves","muscle":"mollets"}]}'::jsonb, true, 1),
  ('jambes_force', 'musculation', 'strength_session', '{"id":"jambes_force","discipline":"musculation","format":"strength_session","target":"jambes","objective":"force","slots":[{"role":"main_compound","muscle":"quadriceps"},{"role":"main_compound","muscle":["ischios","fessiers"]},{"role":"secondary_compound","muscle":"quadriceps","optional":true},{"role":"isolation","muscle":"ischios","optional":true},{"role":"calves","muscle":"mollets","optional":true}]}'::jsonb, true, 1),
  ('jambes_endurance', 'musculation', 'strength_session', '{"id":"jambes_endurance","discipline":"musculation","format":"strength_session","target":"jambes","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"quadriceps"},{"role":"secondary_compound","muscle":["ischios","fessiers"]},{"role":"isolation","muscle":["quadriceps","fessiers"]},{"role":"calves","muscle":"mollets"},{"role":"core","muscle":"tronc","optional":true}]}'::jsonb, true, 1),
  ('bas_hypertrophie', 'musculation', 'strength_session', '{"id":"bas_hypertrophie","discipline":"musculation","format":"strength_session","target":"bas","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"quadriceps"},{"role":"secondary_compound","muscle":"fessiers"},{"role":"secondary_compound","muscle":"ischios"},{"role":"isolation","muscle":["quadriceps","fessiers"]},{"role":"isolation","muscle":"ischios","optional":true},{"role":"core","muscle":["tronc","lombaires"],"optional":true}]}'::jsonb, true, 1),
  ('bas_force', 'musculation', 'strength_session', '{"id":"bas_force","discipline":"musculation","format":"strength_session","target":"bas","objective":"force","slots":[{"role":"main_compound","muscle":"quadriceps"},{"role":"secondary_compound","muscle":"ischios"},{"role":"secondary_compound","muscle":"fessiers","optional":true},{"role":"isolation","muscle":["quadriceps","fessiers"]},{"role":"core","muscle":["lombaires","tronc"],"optional":true}]}'::jsonb, true, 1),
  ('bas_endurance', 'musculation', 'strength_session', '{"id":"bas_endurance","discipline":"musculation","format":"strength_session","target":"bas","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"quadriceps"},{"role":"secondary_compound","muscle":"fessiers"},{"role":"isolation","muscle":["ischios","fessiers"]},{"role":"core","muscle":"tronc"},{"role":"calves","muscle":"mollets","optional":true}]}'::jsonb, true, 1),
  ('full_body_hypertrophie', 'musculation', 'strength_session', '{"id":"full_body_hypertrophie","discipline":"musculation","format":"strength_session","target":"full_body","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"quadriceps"},{"role":"main_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"dos"},{"role":"secondary_compound","muscle":["ischios","fessiers"]},{"role":"isolation","muscle":"epaules","optional":true},{"role":"core","muscle":"tronc","optional":true}]}'::jsonb, true, 1),
  ('full_body_force', 'musculation', 'strength_session', '{"id":"full_body_force","discipline":"musculation","format":"strength_session","target":"full_body","objective":"force","slots":[{"role":"main_compound","muscle":"quadriceps"},{"role":"main_compound","muscle":"pecs"},{"role":"main_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"ischios","optional":true}]}'::jsonb, true, 1),
  ('full_body_endurance', 'musculation', 'strength_session', '{"id":"full_body_endurance","discipline":"musculation","format":"strength_session","target":"full_body","objective":"endurance","slots":[{"role":"secondary_compound","muscle":["quadriceps","fessiers"]},{"role":"secondary_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"dos"},{"role":"secondary_compound","muscle":["ischios","fessiers"]},{"role":"core","muscle":"tronc","optional":true}]}'::jsonb, true, 1),
  ('tronc_hypertrophie', 'musculation', 'strength_session', '{"id":"tronc_hypertrophie","discipline":"musculation","format":"strength_session","target":"tronc","objective":"hypertrophie","slots":[{"role":"core","muscle":"tronc"},{"role":"core","muscle":["obliques","tronc"]},{"role":"core","muscle":"lombaires"},{"role":"core","muscle":"tronc","optional":true}]}'::jsonb, true, 1),
  ('tronc_force', 'musculation', 'strength_session', '{"id":"tronc_force","discipline":"musculation","format":"strength_session","target":"tronc","objective":"force","slots":[{"role":"core","muscle":"tronc"},{"role":"core","muscle":"obliques"},{"role":"core","muscle":"lombaires"},{"role":"core","muscle":"tronc","optional":true}]}'::jsonb, true, 1),
  ('tronc_endurance', 'musculation', 'strength_session', '{"id":"tronc_endurance","discipline":"musculation","format":"strength_session","target":"tronc","objective":"endurance","slots":[{"role":"core","muscle":"tronc","ids":["pallof_press","dead_bug","plank_hold","hollow_hold","ab_wheel","vacuum"]},{"role":"core","muscle":["obliques","tronc"],"ids":["side_plank","db_side_bend","oblique_crunch","hanging_oblique_raise","oblique_bench_raise","rotation_machine","crunch_with_rotation","standing_rotation"]},{"role":"core","muscle":"tronc","ids":["db_farmer_carry","suitcase_carry"]},{"role":"core","muscle":"lombaires"}]}'::jsonb, true, 1),
  ('haut_hypertrophie', 'musculation', 'strength_session', '{"id":"haut_hypertrophie","discipline":"musculation","format":"strength_session","target":"haut","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"pecs"},{"role":"main_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"epaules"},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"epaules_post","optional":true}]}'::jsonb, true, 1),
  ('haut_force', 'musculation', 'strength_session', '{"id":"haut_force","discipline":"musculation","format":"strength_session","target":"haut","objective":"force","slots":[{"role":"main_compound","muscle":"pecs"},{"role":"main_compound","muscle":"epaules"},{"role":"main_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"triceps","optional":true,"ids":["close_grip_bench","close_grip_dips","machine_dips","diamond_push_up","dips"]},{"role":"isolation","muscle":"epaules_post","optional":true}]}'::jsonb, true, 1),
  ('haut_endurance', 'musculation', 'strength_session', '{"id":"haut_endurance","discipline":"musculation","format":"strength_session","target":"haut","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"epaules"},{"role":"isolation","muscle":["biceps","triceps"]},{"role":"core","muscle":"tronc","optional":true}]}'::jsonb, true, 1),
  ('dos_hypertrophie', 'musculation', 'strength_session', '{"id":"dos_hypertrophie","discipline":"musculation","format":"strength_session","target":"dos","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"dos","ids":["strict_pull_up","chin_up","wide_grip_pull_up","neutral_grip_pull_up","close_grip_pull_up","lat_pulldown","converging_pulldown","close_grip_pulldown","supinated_pulldown","one_arm_pulldown"]},{"role":"secondary_compound","muscle":"dos","optional":true},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"trapezes","optional":true},{"role":"isolation","muscle":"lombaires","optional":true}]}'::jsonb, true, 1),
  ('dos_force', 'musculation', 'strength_session', '{"id":"dos_force","discipline":"musculation","format":"strength_session","target":"dos","objective":"force","slots":[{"role":"main_compound","muscle":"dos"},{"role":"main_compound","muscle":"dos","ids":["strict_pull_up","chin_up","wide_grip_pull_up","neutral_grip_pull_up","close_grip_pull_up","lat_pulldown","converging_pulldown","close_grip_pulldown","supinated_pulldown","one_arm_pulldown"]},{"role":"secondary_compound","muscle":"trapezes","optional":true},{"role":"isolation","muscle":"epaules_post","optional":true},{"role":"isolation","muscle":"lombaires","optional":true}]}'::jsonb, true, 1),
  ('dos_endurance', 'musculation', 'strength_session', '{"id":"dos_endurance","discipline":"musculation","format":"strength_session","target":"dos","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"dos"},{"role":"secondary_compound","muscle":"dos","ids":["strict_pull_up","chin_up","wide_grip_pull_up","neutral_grip_pull_up","close_grip_pull_up","lat_pulldown","converging_pulldown","close_grip_pulldown","supinated_pulldown","one_arm_pulldown"]},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"lombaires"},{"role":"isolation","muscle":"trapezes","optional":true}]}'::jsonb, true, 1),
  ('epaules_hypertrophie', 'musculation', 'strength_session', '{"id":"epaules_hypertrophie","discipline":"musculation","format":"strength_session","target":"epaules","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"epaules"},{"role":"isolation","muscle":"epaules"},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"epaules_ant","optional":true},{"role":"isolation","muscle":"trapezes","optional":true}]}'::jsonb, true, 1),
  ('epaules_force', 'musculation', 'strength_session', '{"id":"epaules_force","discipline":"musculation","format":"strength_session","target":"epaules","objective":"force","slots":[{"role":"main_compound","muscle":"epaules"},{"role":"secondary_compound","muscle":"epaules","optional":true},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"epaules","optional":true},{"role":"isolation","muscle":"trapezes","optional":true}]}'::jsonb, true, 1),
  ('epaules_endurance', 'musculation', 'strength_session', '{"id":"epaules_endurance","discipline":"musculation","format":"strength_session","target":"epaules","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"epaules"},{"role":"isolation","muscle":"epaules"},{"role":"isolation","muscle":"epaules_post"},{"role":"isolation","muscle":"epaules_ant","optional":true}]}'::jsonb, true, 1),
  ('bras_hypertrophie', 'musculation', 'strength_session', '{"id":"bras_hypertrophie","discipline":"musculation","format":"strength_session","target":"bras","objective":"hypertrophie","slots":[{"role":"secondary_compound","muscle":"triceps","ids":["close_grip_bench","close_grip_dips","machine_dips","diamond_push_up","dips"]},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"triceps","optional":true},{"role":"isolation","muscle":"avant_bras","optional":true}]}'::jsonb, true, 1),
  ('bras_force', 'musculation', 'strength_session', '{"id":"bras_force","discipline":"musculation","format":"strength_session","target":"bras","objective":"force","slots":[{"role":"main_compound","muscle":"triceps","ids":["close_grip_bench","close_grip_dips","machine_dips","diamond_push_up","dips"]},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"biceps","optional":true},{"role":"isolation","muscle":"avant_bras","optional":true}]}'::jsonb, true, 1),
  ('bras_endurance', 'musculation', 'strength_session', '{"id":"bras_endurance","discipline":"musculation","format":"strength_session","target":"bras","objective":"endurance","slots":[{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"biceps"},{"role":"isolation","muscle":"avant_bras","optional":true}]}'::jsonb, true, 1),
  ('pecs_hypertrophie', 'musculation', 'strength_session', '{"id":"pecs_hypertrophie","discipline":"musculation","format":"strength_session","target":"pecs","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"pecs"},{"role":"isolation","muscle":"pecs"},{"role":"isolation","muscle":"triceps"},{"role":"isolation","muscle":"pecs","optional":true}]}'::jsonb, true, 1),
  ('pecs_force', 'musculation', 'strength_session', '{"id":"pecs_force","discipline":"musculation","format":"strength_session","target":"pecs","objective":"force","slots":[{"role":"main_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"pecs","optional":true},{"role":"secondary_compound","muscle":"triceps","ids":["close_grip_bench","close_grip_dips","machine_dips","diamond_push_up","dips"]},{"role":"isolation","muscle":"pecs","optional":true}]}'::jsonb, true, 1),
  ('pecs_endurance', 'musculation', 'strength_session', '{"id":"pecs_endurance","discipline":"musculation","format":"strength_session","target":"pecs","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"pecs"},{"role":"secondary_compound","muscle":"pecs"},{"role":"isolation","muscle":"pecs"},{"role":"isolation","muscle":"triceps","optional":true}]}'::jsonb, true, 1),
  ('fessiers_hypertrophie', 'musculation', 'strength_session', '{"id":"fessiers_hypertrophie","discipline":"musculation","format":"strength_session","target":"fessiers","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"fessiers","ids":["hip_thrust","db_hip_thrust","hip_thrust_machine","single_leg_hip_thrust","glute_bridge","single_leg_glute_bridge"],"exclude_ids":["back_squat"]},{"role":"secondary_compound","muscle":"ischios","ids":["romanian_deadlift","db_rdl","good_morning","bodyweight_single_leg_rdl"]},{"role":"secondary_compound","muscle":"fessiers","unilateral":true},{"role":"isolation","muscle":["fessiers","ischios"],"ids":["glute_kickback","cable_pull_through","frog_pump","leg_curl","nordic_curl","bodyweight_single_leg_rdl"]},{"role":"isolation","muscle":"fessiers","ids":["hip_abduction_machine","cable_hip_abduction","banded_hip_abduction"]},{"role":"isolation","muscle":"fessiers","optional":true,"ids":["glute_kickback","cable_pull_through","frog_pump"]}]}'::jsonb, true, 1),
  ('fessiers_force', 'musculation', 'strength_session', '{"id":"fessiers_force","discipline":"musculation","format":"strength_session","target":"fessiers","objective":"force","slots":[{"role":"main_compound","muscle":"fessiers","exclude_ids":["back_squat"]},{"role":"main_compound","muscle":"ischios","ids":["romanian_deadlift","db_rdl","good_morning","bodyweight_single_leg_rdl"]},{"role":"secondary_compound","muscle":"fessiers","optional":true,"unilateral":true},{"role":"isolation","muscle":"fessiers","optional":true},{"role":"core","muscle":"lombaires","optional":true}]}'::jsonb, true, 1),
  ('fessiers_endurance', 'musculation', 'strength_session', '{"id":"fessiers_endurance","discipline":"musculation","format":"strength_session","target":"fessiers","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"fessiers","exclude_ids":["back_squat"]},{"role":"secondary_compound","muscle":"ischios"},{"role":"isolation","muscle":"fessiers"},{"role":"isolation","muscle":["ischios","fessiers"]},{"role":"core","muscle":"lombaires","optional":true}]}'::jsonb, true, 1),
  ('fessiers_ischios_hypertrophie', 'musculation', 'strength_session', '{"id":"fessiers_ischios_hypertrophie","discipline":"musculation","format":"strength_session","target":"fessiers_ischios","objective":"hypertrophie","slots":[{"role":"main_compound","muscle":"ischios","ids":["romanian_deadlift","db_rdl","good_morning","bodyweight_single_leg_rdl"]},{"role":"main_compound","muscle":"fessiers","ids":["hip_thrust","db_hip_thrust","hip_thrust_machine","single_leg_hip_thrust","glute_bridge","single_leg_glute_bridge"]},{"role":"secondary_compound","muscle":["fessiers","ischios"],"unilateral":true},{"role":"isolation","muscle":"ischios","ids":["leg_curl","nordic_curl","bodyweight_single_leg_rdl"]},{"role":"isolation","muscle":"fessiers","ids":["hip_abduction_machine","cable_hip_abduction","banded_hip_abduction"]}]}'::jsonb, true, 1),
  ('fessiers_ischios_force', 'musculation', 'strength_session', '{"id":"fessiers_ischios_force","discipline":"musculation","format":"strength_session","target":"fessiers_ischios","objective":"force","slots":[{"role":"main_compound","muscle":"ischios","ids":["romanian_deadlift","db_rdl","good_morning","bodyweight_single_leg_rdl"]},{"role":"main_compound","muscle":"fessiers","exclude_ids":["back_squat"]},{"role":"secondary_compound","muscle":["fessiers","ischios"],"optional":true},{"role":"isolation","muscle":"ischios","optional":true},{"role":"core","muscle":"lombaires","optional":true}]}'::jsonb, true, 1),
  ('fessiers_ischios_endurance', 'musculation', 'strength_session', '{"id":"fessiers_ischios_endurance","discipline":"musculation","format":"strength_session","target":"fessiers_ischios","objective":"endurance","slots":[{"role":"secondary_compound","muscle":"ischios"},{"role":"secondary_compound","muscle":"fessiers"},{"role":"isolation","muscle":"fessiers"},{"role":"isolation","muscle":"ischios"},{"role":"core","muscle":"lombaires","optional":true}]}'::jsonb, true, 1)
ON CONFLICT (id) DO UPDATE SET
  discipline = EXCLUDED.discipline, format = EXCLUDED.format, definition = EXCLUDED.definition,
  active = EXCLUDED.active, version = EXCLUDED.version, updated_at = now();
