-- ═════════════════════════════════════════════════════════════════════════════
-- Générateur de WOD v1 — catalogue de mouvements + historique structuré.
--
-- FICHIER GÉNÉRÉ par packages/wod-engine/scripts/import-catalog.cjs depuis
-- packages/wod-engine/catalog/catalogue-v1.csv (DDL : scripts/movement_catalog.ddl.sql).
-- Ne pas éditer à la main : relancer le script.
--
-- Appliquée en prod : NON (dump avant toute application).
--
-- Additif et rejouable :
--   1. `movement_catalog` — un mouvement par ligne, la source du tirage ET
--      du back-office (PR 3). Les mouvements de l'ancien catalogue app absents
--      du CSV y figurent avec `active = false` (crédit de badges, back-office).
--      `Weighted Vest` n'y est pas : le gilet est un paramètre de génération.
--   2. `generated_wods.wod_json` — le WOD structuré complet (`GeneratedWod`,
--      rounds et signature inclus). Les colonnes texte existantes restent le
--      rendu lisible ; l'anti-répétition lit `wod_json->>'signature'`.
--
-- Lecture : tout utilisateur connecté (le générateur tourne sur l'appareil).
-- Écriture : service_role uniquement (import / back-office signé, PR 3).
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.movement_catalog (
  id                text PRIMARY KEY,
  name              text NOT NULL UNIQUE,
  family            text NOT NULL
    CHECK (family IN ('barbell','dumbbell','kettlebell','gym','bodyweight','erg','run','sled','carry','sandbag','wallball','jump_rope','box','other')),
  pattern           text[] NOT NULL DEFAULT '{}'
    CHECK (pattern <@ ARRAY['squat','hinge','push_v','push_h','pull_v','pull_h','carry','lunge','core','mono']::text[]),
  modality          text NOT NULL CHECK (modality IN ('W','G','M')),
  grip              text NOT NULL CHECK (grip IN ('none','low','high')),
  shoulder_load     text NOT NULL CHECK (shoulder_load IN ('none','low','high')),
  unit_default      text NOT NULL CHECK (unit_default IN ('reps','cal','m','s')),
  units_allowed     text[] NOT NULL DEFAULT '{reps}'
    CHECK (units_allowed <@ ARRAY['reps','cal','m','s']::text[] AND unit_default = ANY (units_allowed)),
  load_unit         text CHECK (load_unit IN ('kg','cm')),
  weight_functional smallint NOT NULL DEFAULT 0 CHECK (weight_functional BETWEEN 0 AND 10),
  weight_hybrid     smallint NOT NULL DEFAULT 0 CHECK (weight_hybrid BETWEEN 0 AND 10),
  equipment         text[] NOT NULL DEFAULT '{}',
  -- { "rx": { "cal": 3.6, "m": 0.2 }, ... } — secondes par unité, par catégorie Functional
  cadence           jsonb,
  -- { "rx": { "light": [43, 30], "medium": [...], "heavy": [...] }, ... } — [H, F]
  loads             jsonb,
  -- { "reps": { "amrap": [9, 15], "for_time": [...], "emom": [...], "interval": [...] }, "m": {...} }
  rep_ranges        jsonb,
  -- { "scaled": "box_step_up", "inter": "..." } — id de remplacement par catégorie
  substitutions     jsonb,
  variant_up        text REFERENCES public.movement_catalog(id),
  badge_key         text,
  active            boolean NOT NULL DEFAULT true,
  version           integer NOT NULL DEFAULT 1,
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.movement_catalog IS
  'Catalogue de mouvements du générateur de WOD (catalogue-v1). active=false : mouvement de l''ancien catalogue app, gardé pour les badges et le back-office, jamais tiré.';
COMMENT ON COLUMN public.movement_catalog.badge_key IS
  'Préfixe de badge (mv_*) rempli depuis MOVEMENT_BADGE_PREFIX / CARDIO_BADGE_PREFIX ; null = pas de badge.';
COMMENT ON COLUMN public.movement_catalog.cadence IS
  'Secondes par unité par catégorie Functional puis par unité : {"rx":{"cal":3.6,"m":0.2}}. Hybrid : Women/Men → rx, Pro → rxplus.';
COMMENT ON COLUMN public.movement_catalog.loads IS
  'Charges [H,F] par catégorie Functional et bande light/medium/heavy. Hybrid : Women = rx[F], Men = rx[H], Pro = rxplus.';

CREATE INDEX IF NOT EXISTS idx_movement_catalog_active ON public.movement_catalog (active) WHERE active;
CREATE INDEX IF NOT EXISTS idx_movement_catalog_family ON public.movement_catalog (family);

CREATE OR REPLACE FUNCTION public.movement_catalog_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS movement_catalog_touch_updated_at ON public.movement_catalog;
CREATE TRIGGER movement_catalog_touch_updated_at
  BEFORE UPDATE ON public.movement_catalog
  FOR EACH ROW EXECUTE FUNCTION public.movement_catalog_touch_updated_at();

ALTER TABLE public.movement_catalog ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS movement_catalog_select_authenticated ON public.movement_catalog;
CREATE POLICY movement_catalog_select_authenticated ON public.movement_catalog
  FOR SELECT TO authenticated USING (true);

REVOKE ALL ON TABLE public.movement_catalog FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.movement_catalog TO authenticated;
GRANT ALL ON TABLE public.movement_catalog TO service_role;

-- ─── Historique : le WOD structuré à côté du rendu texte ─────────────────────
ALTER TABLE public.generated_wods
  ADD COLUMN IF NOT EXISTS wod_json jsonb;

COMMENT ON COLUMN public.generated_wods.wod_json IS
  'GeneratedWod complet (packages/wod-engine) : blocs, rounds, estimation, signature. Les colonnes texte restent le rendu.';

CREATE INDEX IF NOT EXISTS idx_gen_wods_user_signature
  ON public.generated_wods (user_id, created_at DESC)
  WHERE wod_json IS NOT NULL;

-- ── Seed : catalogue-v1 (109 lignes, généré par packages/wod-engine/scripts/import-catalog.cjs) ──
INSERT INTO public.movement_catalog
  (id, name, family, pattern, modality, grip, shoulder_load, unit_default, units_allowed,
   load_unit, weight_functional, weight_hybrid, equipment, cadence, loads, rep_ranges, substitutions,
   variant_up, badge_key, active, version, notes)
VALUES
  ('thruster', 'Thruster', 'barbell', ARRAY['squat', 'push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 9, 2, ARRAY['barbell']::text[], '{"scaled":{"reps":4.16},"inter":{"reps":3.68},"rx":{"reps":3.2},"rxplus":{"reps":2.94},"elite":{"reps":2.72},"pro":{"reps":2.56}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[60,43]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[70,50]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[80,55]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[90,60]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[9,15],"for_time":[9,21],"emom":[5,10],"interval":[8,12]}}'::jsonb, NULL, NULL, 'mv_thrusters', true, 2, 'bench 21-15-9 = Fran'),
  ('power_snatch', 'Power Snatch', 'barbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 8, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":4.55},"inter":{"reps":4.02},"rx":{"reps":3.5},"rxplus":{"reps":3.22},"elite":{"reps":2.98},"pro":{"reps":2.8}}'::jsonb, '{"scaled":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"inter":{"light":[25,20],"medium":[35,25],"heavy":[50,35]},"rx":{"light":[30,20],"medium":[43,30],"heavy":[60,43]},"rxplus":{"light":[35,25],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[40,30],"medium":[55,40],"heavy":[80,55]},"pro":{"light":[43,30],"medium":[60,43],"heavy":[90,60]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[3,7],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_snatch', true, 2, NULL),
  ('hang_power_snatch', 'Hang Power Snatch', 'barbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 6, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"inter":{"light":[25,20],"medium":[35,25],"heavy":[50,35]},"rx":{"light":[30,20],"medium":[43,30],"heavy":[60,43]},"rxplus":{"light":[35,25],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[40,30],"medium":[55,40],"heavy":[80,55]},"pro":{"light":[43,30],"medium":[60,43],"heavy":[90,60]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('squat_snatch', 'Squat Snatch', 'barbell', ARRAY['hinge', 'squat']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 5, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":6.5},"inter":{"reps":5.75},"rx":{"reps":5},"rxplus":{"reps":4.6},"elite":{"reps":4.25},"pro":{"reps":4}}'::jsonb, '{"scaled":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"inter":{"light":[25,20],"medium":[35,25],"heavy":[50,35]},"rx":{"light":[30,20],"medium":[43,30],"heavy":[60,43]},"rxplus":{"light":[35,25],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[40,30],"medium":[55,40],"heavy":[80,55]},"pro":{"light":[43,30],"medium":[60,43],"heavy":[90,60]}}'::jsonb, '{"reps":{"amrap":[3,8],"for_time":[3,10],"emom":[2,5],"interval":[3,6]}}'::jsonb, NULL, NULL, 'mv_snatch', true, 2, NULL),
  ('overhead_squat', 'Overhead Squat', 'barbell', ARRAY['squat']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 6, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"inter":{"light":[25,20],"medium":[35,25],"heavy":[50,35]},"rx":{"light":[30,20],"medium":[43,30],"heavy":[60,43]},"rxplus":{"light":[35,25],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[40,30],"medium":[55,40],"heavy":[80,55]},"pro":{"light":[43,30],"medium":[60,43],"heavy":[90,60]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[9,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_ohs', true, 2, NULL),
  ('power_clean', 'Power Clean', 'barbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 9, 1, ARRAY['barbell']::text[], '{"scaled":{"reps":4.55},"inter":{"reps":4.02},"rx":{"reps":3.5},"rxplus":{"reps":3.22},"elite":{"reps":2.98},"pro":{"reps":2.8}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[60,40]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[80,55]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[100,70]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[120,80]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[140,95]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[160,110]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[3,7],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_clean', true, 2, NULL),
  ('hang_power_clean', 'Hang Power Clean', 'barbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 7, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[60,40]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[80,55]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[100,70]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[120,80]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[140,95]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[140,85]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_clean', true, 2, NULL),
  ('squat_clean', 'Squat Clean', 'barbell', ARRAY['hinge', 'squat']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":6.5},"inter":{"reps":5.75},"rx":{"reps":5},"rxplus":{"reps":4.6},"elite":{"reps":4.25},"pro":{"reps":4}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[60,40]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[80,55]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[100,70]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[120,80]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[140,95]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[160,110]}}'::jsonb, '{"reps":{"amrap":[3,8],"for_time":[3,10],"emom":[2,5],"interval":[3,6]}}'::jsonb, NULL, NULL, 'mv_clean', true, 2, NULL),
  ('clean_and_jerk', 'Clean & Jerk', 'barbell', ARRAY['hinge', 'push_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 7, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":7.15},"inter":{"reps":6.32},"rx":{"reps":5.5},"rxplus":{"reps":5.06},"elite":{"reps":4.67},"pro":{"reps":4.4}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[60,40]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[80,55]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[100,70]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[120,80]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[140,95]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[160,110]}}'::jsonb, '{"reps":{"amrap":[3,8],"for_time":[3,10],"emom":[2,5],"interval":[3,6]}}'::jsonb, NULL, NULL, 'mv_cj', true, 2, 'bench 30 for time = Grace'),
  ('push_press', 'Push Press', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 7, 1, ARRAY['barbell']::text[], '{"scaled":{"reps":3.25},"inter":{"reps":2.88},"rx":{"reps":2.5},"rxplus":{"reps":2.3},"elite":{"reps":2.12},"pro":{"reps":2}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[60,43]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[70,50]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[80,55]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[90,60]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[9,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_press', true, 2, NULL),
  ('push_jerk', 'Push Jerk', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 5, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":3.64},"inter":{"reps":3.22},"rx":{"reps":2.8},"rxplus":{"reps":2.58},"elite":{"reps":2.38},"pro":{"reps":2.24}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[60,43]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[70,50]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[80,55]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[90,60]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_press', true, 2, NULL),
  ('shoulder_to_overhead', 'Shoulder To Overhead', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 8, 1, ARRAY['barbell']::text[], '{"scaled":{"reps":3.64},"inter":{"reps":3.22},"rx":{"reps":2.8},"rxplus":{"reps":2.58},"elite":{"reps":2.38},"pro":{"reps":2.24}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[60,43]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[70,50]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[80,55]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[90,60]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[9,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_press', true, 2, NULL),
  ('front_squat', 'Front Squat', 'barbell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 7, 1, ARRAY['barbell']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[40,30],"medium":[50,35],"heavy":[60,40]},"inter":{"light":[50,35],"medium":[60,43],"heavy":[80,55]},"rx":{"light":[60,43],"medium":[70,50],"heavy":[100,70]},"rxplus":{"light":[70,50],"medium":[80,55],"heavy":[120,80]},"elite":{"light":[80,55],"medium":[90,60],"heavy":[140,95]},"pro":{"light":[90,60],"medium":[100,70],"heavy":[160,110]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_squat', true, 2, NULL),
  ('back_squat', 'Back Squat', 'barbell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 1, ARRAY['barbell', 'rack']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[40,30],"medium":[60,40],"heavy":[80,55]},"inter":{"light":[50,35],"medium":[80,55],"heavy":[100,70]},"rx":{"light":[60,43],"medium":[100,70],"heavy":[140,95]},"rxplus":{"light":[70,50],"medium":[120,80],"heavy":[160,110]},"elite":{"light":[80,55],"medium":[140,95],"heavy":[180,120]},"pro":{"light":[90,60],"medium":[160,110],"heavy":[200,140]}}'::jsonb, '{"reps":{"amrap":[5,10],"for_time":[5,15],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, 'mv_squat', true, 2, NULL),
  ('deadlift', 'Deadlift', 'barbell', ARRAY['hinge']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 9, 2, ARRAY['barbell']::text[], '{"scaled":{"reps":3.25},"inter":{"reps":2.88},"rx":{"reps":2.5},"rxplus":{"reps":2.3},"elite":{"reps":2.12},"pro":{"reps":2}}'::jsonb, '{"scaled":{"light":[50,35],"medium":[60,40],"heavy":[80,55]},"inter":{"light":[60,43],"medium":[80,55],"heavy":[100,70]},"rx":{"light":[70,50],"medium":[100,70],"heavy":[140,95]},"rxplus":{"light":[80,55],"medium":[120,80],"heavy":[160,110]},"elite":{"light":[90,60],"medium":[140,95],"heavy":[180,120]},"pro":{"light":[100,70],"medium":[160,110],"heavy":[200,140]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,21],"emom":[3,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_deadlifts', true, 2, 'bench 21-15-9 = Diane'),
  ('sumo_deadlift_high_pull', 'Sumo Deadlift High Pull', 'barbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, '{"scaled":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"inter":{"light":[25,20],"medium":[35,25],"heavy":[50,35]},"rx":{"light":[30,20],"medium":[43,30],"heavy":[60,43]},"rxplus":{"light":[35,25],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[40,30],"medium":[55,40],"heavy":[80,55]},"pro":{"light":[43,30],"medium":[60,43],"heavy":[90,60]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[9,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_sdlhp', true, 2, NULL),
  ('bench_press', 'Bench Press', 'barbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 4, 0, ARRAY['barbell', 'bench']::text[], '{"scaled":{"reps":3.64},"inter":{"reps":3.22},"rx":{"reps":2.8},"rxplus":{"reps":2.58},"elite":{"reps":2.38},"pro":{"reps":2.24}}'::jsonb, '{"scaled":{"light":[40,30],"medium":[50,35],"heavy":[60,40]},"inter":{"light":[50,35],"medium":[60,43],"heavy":[80,55]},"rx":{"light":[60,43],"medium":[70,50],"heavy":[100,70]},"rxplus":{"light":[70,50],"medium":[80,55],"heavy":[120,80]},"elite":{"light":[80,55],"medium":[90,60],"heavy":[140,95]},"pro":{"light":[90,60],"medium":[100,70],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[5,10],"for_time":[5,15],"emom":[3,8],"interval":[4,8]}}'::jsonb, NULL, NULL, 'mv_bench_press', true, 2, NULL),
  ('front_rack_lunge', 'Front Rack Lunges', 'barbell', ARRAY['lunge']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 6, 2, ARRAY['barbell']::text[], '{"scaled":{"reps":3.25},"inter":{"reps":2.88},"rx":{"reps":2.5},"rxplus":{"reps":2.3},"elite":{"reps":2.12},"pro":{"reps":2}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[60,43]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[70,50]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[80,55]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[90,60]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, NULL, true, 2, 'reps = pas au total'),
  ('bar_facing_burpee', 'Bar Facing Burpees', 'bodyweight', ARRAY['core', 'mono']::text[], 'M', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 8, 2, ARRAY['barbell']::text[], '{"scaled":{"reps":5.85},"inter":{"reps":5.17},"rx":{"reps":4.5},"rxplus":{"reps":4.14},"elite":{"reps":3.82},"pro":{"reps":3.6}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_burpee', true, 2, NULL),
  ('kb_swing_american', 'KB Swing', 'kettlebell', ARRAY['hinge']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 8, 4, ARRAY['kettlebell']::text[], '{"scaled":{"reps":2.6},"inter":{"reps":2.3},"rx":{"reps":2},"rxplus":{"reps":1.84},"elite":{"reps":1.7},"pro":{"reps":1.6}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[10,25],"for_time":[15,30],"emom":[8,15],"interval":[10,20]}}'::jsonb, NULL, NULL, 'mv_kb_swing', true, 2, NULL),
  ('kb_swing_russian', 'KB Swings Russian', 'kettlebell', ARRAY['hinge']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 6, 5, ARRAY['kettlebell']::text[], '{"scaled":{"reps":2.34},"inter":{"reps":2.07},"rx":{"reps":1.8},"rxplus":{"reps":1.66},"elite":{"reps":1.53},"pro":{"reps":1.44}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[10,25],"for_time":[15,30],"emom":[8,15],"interval":[10,20]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('kb_goblet_squat', 'Goblet Squat', 'kettlebell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 4, ARRAY['kettlebell']::text[], '{"scaled":{"reps":3.25},"inter":{"reps":2.88},"rx":{"reps":2.5},"rxplus":{"reps":2.3},"elite":{"reps":2.12},"pro":{"reps":2}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,25],"emom":[6,12],"interval":[8,15]}}'::jsonb, NULL, NULL, 'mv_goblet_squat', true, 2, NULL),
  ('db_snatch', 'Alt DB Snatch', 'dumbbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 8, 3, ARRAY['dumbbell']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, '{"scaled":{"light":[10,7.5],"medium":[15,10],"heavy":[20,12.5]},"inter":{"light":[12.5,10],"medium":[20,12.5],"heavy":[22.5,15]},"rx":{"light":[15,10],"medium":[22.5,15],"heavy":[30,20]},"rxplus":{"light":[20,12.5],"medium":[30,20],"heavy":[35,22.5]},"elite":{"light":[22.5,15],"medium":[35,22.5],"heavy":[40,25]},"pro":{"light":[22.5,15],"medium":[40,25],"heavy":[50,30]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, NULL, true, 2, 'alterné, reps au total'),
  ('db_thruster', 'DB Thruster', 'dumbbell', ARRAY['squat', 'push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 7, 3, ARRAY['dumbbell']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[10,7.5],"medium":[15,10],"heavy":[20,12.5]},"inter":{"light":[12.5,10],"medium":[20,12.5],"heavy":[22.5,15]},"rx":{"light":[15,10],"medium":[22.5,15],"heavy":[30,20]},"rxplus":{"light":[20,12.5],"medium":[30,20],"heavy":[35,22.5]},"elite":{"light":[22.5,15],"medium":[35,22.5],"heavy":[40,25]},"pro":{"light":[22.5,15],"medium":[40,25],"heavy":[50,30]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[9,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_db_thruster', true, 2, '2 DB'),
  ('db_clean_and_jerk', 'DB Clean & Jerk', 'dumbbell', ARRAY['hinge', 'push_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 6, 3, ARRAY['dumbbell']::text[], '{"scaled":{"reps":4.55},"inter":{"reps":4.02},"rx":{"reps":3.5},"rxplus":{"reps":3.22},"elite":{"reps":2.98},"pro":{"reps":2.8}}'::jsonb, '{"scaled":{"light":[10,7.5],"medium":[15,10],"heavy":[20,12.5]},"inter":{"light":[12.5,10],"medium":[20,12.5],"heavy":[22.5,15]},"rx":{"light":[15,10],"medium":[22.5,15],"heavy":[30,20]},"rxplus":{"light":[20,12.5],"medium":[30,20],"heavy":[35,22.5]},"elite":{"light":[22.5,15],"medium":[35,22.5],"heavy":[40,25]},"pro":{"light":[22.5,15],"medium":[40,25],"heavy":[50,30]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[6,15],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_db_cj', true, 2, '2 DB'),
  ('db_box_step_over', 'DB Box Step Over', 'dumbbell', ARRAY['lunge']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 6, 6, ARRAY['dumbbell', 'box']::text[], '{"scaled":{"reps":5.2},"inter":{"reps":4.6},"rx":{"reps":4},"rxplus":{"reps":3.68},"elite":{"reps":3.4},"pro":{"reps":3.2}}'::jsonb, '{"scaled":{"light":[10,7.5],"medium":[15,10],"heavy":[20,12.5]},"inter":{"light":[12.5,10],"medium":[20,12.5],"heavy":[22.5,15]},"rx":{"light":[15,10],"medium":[22.5,15],"heavy":[30,20]},"rxplus":{"light":[20,12.5],"medium":[30,20],"heavy":[35,22.5]},"elite":{"light":[22.5,15],"medium":[35,22.5],"heavy":[40,25]},"pro":{"light":[22.5,15],"medium":[40,25],"heavy":[50,30]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[8,15],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('db_lunge', 'DB Lunges', 'dumbbell', ARRAY['lunge']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 6, 7, ARRAY['dumbbell']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, '{"scaled":{"light":[10,7.5],"medium":[15,10],"heavy":[20,12.5]},"inter":{"light":[12.5,10],"medium":[20,12.5],"heavy":[22.5,15]},"rx":{"light":[15,10],"medium":[22.5,15],"heavy":[30,20]},"rxplus":{"light":[20,12.5],"medium":[30,20],"heavy":[35,22.5]},"elite":{"light":[22.5,15],"medium":[35,22.5],"heavy":[40,25]},"pro":{"light":[22.5,15],"medium":[40,25],"heavy":[50,30]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, 'mv_lunge', true, 2, 'reps = pas au total'),
  ('devil_press', 'Devils Press', 'dumbbell', ARRAY['hinge', 'push_v', 'core']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 5, 4, ARRAY['dumbbell']::text[], '{"scaled":{"reps":7.8},"inter":{"reps":6.9},"rx":{"reps":6},"rxplus":{"reps":5.52},"elite":{"reps":5.1},"pro":{"reps":4.8}}'::jsonb, '{"scaled":{"light":[10,7.5],"medium":[15,10],"heavy":[20,12.5]},"inter":{"light":[12.5,10],"medium":[20,12.5],"heavy":[22.5,15]},"rx":{"light":[15,10],"medium":[22.5,15],"heavy":[30,20]},"rxplus":{"light":[20,12.5],"medium":[30,20],"heavy":[35,22.5]},"elite":{"light":[22.5,15],"medium":[35,22.5],"heavy":[40,25]},"pro":{"light":[22.5,15],"medium":[40,25],"heavy":[50,30]}}'::jsonb, '{"reps":{"amrap":[5,10],"for_time":[6,12],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, 'mv_devil_press', true, 2, NULL),
  ('db_farmer_carry', 'Farmer Carry', 'carry', ARRAY['carry']::text[], 'W', 'high', 'none', 'm', ARRAY['m']::text[], 'kg', 4, 9, ARRAY['kettlebell', 'dumbbell']::text[], '{"scaled":{"m":1.1},"inter":{"m":0.98},"rx":{"m":0.85},"rxplus":{"m":0.78},"elite":{"m":0.72},"pro":{"m":0.68}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"m":{"amrap":[50,200],"for_time":[50,200],"emom":[40,60],"interval":[50,100]}}'::jsonb, NULL, NULL, NULL, true, 2, 'charge par main'),
  ('wall_ball', 'Wall Balls', 'wallball', ARRAY['squat', 'push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 9, 8, ARRAY['wallball']::text[], '{"scaled":{"reps":3.25},"inter":{"reps":2.88},"rx":{"reps":2.5},"rxplus":{"reps":2.3},"elite":{"reps":2.12},"pro":{"reps":2}}'::jsonb, '{"scaled":{"light":[4,3],"medium":[6,4],"heavy":[9,6]},"inter":{"light":[6,4],"medium":[9,6],"heavy":[9,6]},"rx":{"light":[6,4],"medium":[9,6],"heavy":[14,9]},"rxplus":{"light":[9,6],"medium":[12,9],"heavy":[14,9]},"elite":{"light":[9,6],"medium":[14,9],"heavy":[20,14]},"pro":{"light":[9,6],"medium":[14,9],"heavy":[20,14]}}'::jsonb, '{"reps":{"amrap":[10,25],"for_time":[15,50],"emom":[8,15],"interval":[10,20]}}'::jsonb, NULL, NULL, 'mv_wallball', true, 2, 'cible 3.05 m H / 2.75 m F ; Hyrox 100 reps race'),
  ('sandbag_lunge', 'Sandbag Lunges', 'sandbag', ARRAY['lunge']::text[], 'W', 'low', 'high', 'm', ARRAY['m']::text[], 'kg', 3, 9, ARRAY['sandbag']::text[], '{"scaled":{"m":2.6},"inter":{"m":2.3},"rx":{"m":2},"rxplus":{"m":1.84},"elite":{"m":1.7},"pro":{"m":1.6}}'::jsonb, '{"scaled":{"light":[15,10],"medium":[20,15],"heavy":[30,20]},"inter":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"rx":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"rxplus":{"light":[40,30],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[50,35],"medium":[60,45],"heavy":[80,60]},"pro":{"light":[50,35],"medium":[70,50],"heavy":[100,70]}}'::jsonb, '{"m":{"amrap":[20,50],"for_time":[25,100],"emom":[15,25],"interval":[20,40]}}'::jsonb, NULL, NULL, NULL, true, 2, 'Hyrox 100 m race'),
  ('sandbag_carry', 'Sandbag Carry', 'carry', ARRAY['carry']::text[], 'W', 'low', 'high', 'm', ARRAY['m']::text[], 'kg', 3, 8, ARRAY['sandbag']::text[], '{"scaled":{"m":0.91},"inter":{"m":0.8},"rx":{"m":0.7},"rxplus":{"m":0.64},"elite":{"m":0.59},"pro":{"m":0.56}}'::jsonb, '{"scaled":{"light":[15,10],"medium":[20,15],"heavy":[30,20]},"inter":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"rx":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"rxplus":{"light":[40,30],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[50,35],"medium":[60,45],"heavy":[80,60]},"pro":{"light":[50,35],"medium":[70,50],"heavy":[100,70]}}'::jsonb, '{"m":{"amrap":[50,200],"for_time":[50,200],"emom":[40,60],"interval":[50,100]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('sandbag_clean', 'Sandbag Cleans', 'sandbag', ARRAY['hinge']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 4, 6, ARRAY['sandbag']::text[], '{"scaled":{"reps":5.2},"inter":{"reps":4.6},"rx":{"reps":4},"rxplus":{"reps":3.68},"elite":{"reps":3.4},"pro":{"reps":3.2}}'::jsonb, '{"scaled":{"light":[15,10],"medium":[20,15],"heavy":[30,20]},"inter":{"light":[20,15],"medium":[30,20],"heavy":[40,30]},"rx":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"rxplus":{"light":[40,30],"medium":[50,35],"heavy":[70,50]},"elite":{"light":[50,35],"medium":[60,45],"heavy":[80,60]},"pro":{"light":[50,35],"medium":[70,50],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[5,12],"for_time":[6,15],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('sandbag_over_shoulder', 'Sandbag Over Shoulder', 'sandbag', ARRAY['hinge']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 3, 5, ARRAY['sandbag']::text[], '{"scaled":{"reps":5.85},"inter":{"reps":5.17},"rx":{"reps":4.5},"rxplus":{"reps":4.14},"elite":{"reps":3.82},"pro":{"reps":3.6}}'::jsonb, '{"scaled":{"light":[20,15],"medium":[30,20],"heavy":[30,20]},"inter":{"light":[30,20],"medium":[40,30],"heavy":[40,30]},"rx":{"light":[40,30],"medium":[50,35],"heavy":[50,35]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[70,50]},"elite":{"light":[60,45],"medium":[80,60],"heavy":[80,60]},"pro":{"light":[70,50],"medium":[100,70],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[5,10],"for_time":[6,15],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('sled_push', 'Sled Push', 'sled', ARRAY['squat', 'push_h']::text[], 'W', 'none', 'low', 'm', ARRAY['m']::text[], 'kg', 4, 10, ARRAY['sled']::text[], '{"scaled":{"m":2.86},"inter":{"m":2.53},"rx":{"m":2.2},"rxplus":{"m":2.02},"elite":{"m":1.87},"pro":{"m":1.76}}'::jsonb, '{"scaled":{"light":[50,35],"medium":[75,50],"heavy":[100,75]},"inter":{"light":[75,50],"medium":[100,75],"heavy":[125,100]},"rx":{"light":[100,75],"medium":[125,100],"heavy":[150,125]},"rxplus":{"light":[125,100],"medium":[150,125],"heavy":[175,150]},"elite":{"light":[150,125],"medium":[175,150],"heavy":[200,175]},"pro":{"light":[150,125],"medium":[200,150],"heavy":[250,200]}}'::jsonb, '{"m":{"amrap":[20,50],"for_time":[25,100],"emom":[15,25],"interval":[20,40]}}'::jsonb, NULL, NULL, NULL, true, 2, 'charge sled incluse ; Hyrox 50 m race'),
  ('sled_pull', 'Sled Pull', 'sled', ARRAY['pull_h', 'hinge']::text[], 'W', 'high', 'low', 'm', ARRAY['m']::text[], 'kg', 3, 10, ARRAY['sled', 'rope']::text[], '{"scaled":{"m":3.38},"inter":{"m":2.99},"rx":{"m":2.6},"rxplus":{"m":2.39},"elite":{"m":2.21},"pro":{"m":2.08}}'::jsonb, '{"scaled":{"light":[40,30],"medium":[50,40],"heavy":[75,50]},"inter":{"light":[50,40],"medium":[75,50],"heavy":[100,75]},"rx":{"light":[75,50],"medium":[100,75],"heavy":[125,100]},"rxplus":{"light":[100,75],"medium":[125,100],"heavy":[150,125]},"elite":{"light":[100,75],"medium":[150,125],"heavy":[175,150]},"pro":{"light":[125,100],"medium":[150,125],"heavy":[200,150]}}'::jsonb, '{"m":{"amrap":[20,50],"for_time":[25,100],"emom":[15,25],"interval":[20,40]}}'::jsonb, NULL, NULL, NULL, true, 2, 'Hyrox 50 m race'),
  ('row', 'Row', 'erg', ARRAY['mono', 'pull_h']::text[], 'M', 'low', 'none', 'cal', ARRAY['cal', 'm']::text[], NULL, 9, 9, ARRAY['rower']::text[], '{"scaled":{"cal":4.68,"m":0.26},"inter":{"cal":4.14,"m":0.23},"rx":{"cal":3.6,"m":0.2},"rxplus":{"cal":3.31,"m":0.184},"elite":{"cal":3.06,"m":0.17},"pro":{"cal":2.88,"m":0.16}}'::jsonb, NULL, '{"cal":{"amrap":[10,25],"for_time":[12,50],"emom":[8,15],"interval":[10,20]},"m":{"amrap":[200,500],"for_time":[250,1000],"emom":[150,250],"interval":[200,500]}}'::jsonb, NULL, NULL, 'mv_row', true, 2, 'cal ; 1 cal ≈ 18 m ; Hyrox 1000 m race'),
  ('bike_erg', 'Bike Erg', 'erg', ARRAY['mono']::text[], 'M', 'none', 'none', 'cal', ARRAY['cal', 'm']::text[], NULL, 8, 7, ARRAY['bike_erg']::text[], '{"scaled":{"cal":4.29,"m":0.117},"inter":{"cal":3.79,"m":0.103},"rx":{"cal":3.3,"m":0.09},"rxplus":{"cal":3.04,"m":0.083},"elite":{"cal":2.8,"m":0.076},"pro":{"cal":2.64,"m":0.072}}'::jsonb, NULL, '{"cal":{"amrap":[12,30],"for_time":[15,60],"emom":[10,18],"interval":[12,25]},"m":{"amrap":[500,1500],"for_time":[500,2000],"emom":[300,600],"interval":[500,1000]}}'::jsonb, NULL, NULL, 'mv_bike', true, 2, NULL),
  ('echo_bike', 'Echo Bike', 'erg', ARRAY['mono']::text[], 'M', 'none', 'low', 'cal', ARRAY['cal']::text[], NULL, 8, 6, ARRAY['echo_bike']::text[], '{"scaled":{"cal":4.55},"inter":{"cal":4.02},"rx":{"cal":3.5},"rxplus":{"cal":3.22},"elite":{"cal":2.98},"pro":{"cal":2.8}}'::jsonb, NULL, '{"cal":{"amrap":[10,25],"for_time":[12,50],"emom":[8,14],"interval":[10,20]}}'::jsonb, NULL, NULL, 'mv_bike', true, 2, 'cal F ≈ 0.8 × cal H, à gérer dans le rendu'),
  ('ski_erg', 'SkiErg', 'erg', ARRAY['mono', 'pull_v', 'core']::text[], 'M', 'low', 'high', 'cal', ARRAY['cal', 'm']::text[], NULL, 7, 9, ARRAY['ski_erg']::text[], '{"scaled":{"cal":4.94,"m":0.273},"inter":{"cal":4.37,"m":0.242},"rx":{"cal":3.8,"m":0.21},"rxplus":{"cal":3.5,"m":0.193},"elite":{"cal":3.23,"m":0.179},"pro":{"cal":3.04,"m":0.168}}'::jsonb, NULL, '{"cal":{"amrap":[10,25],"for_time":[12,50],"emom":[8,14],"interval":[10,20]},"m":{"amrap":[200,500],"for_time":[250,1000],"emom":[150,250],"interval":[200,500]}}'::jsonb, NULL, NULL, 'mv_ski', true, 2, 'Hyrox 1000 m race'),
  ('run', 'Run', 'run', ARRAY['mono']::text[], 'M', 'none', 'none', 'm', ARRAY['m']::text[], NULL, 7, 10, ARRAY[]::text[], '{"scaled":{"m":0.35},"inter":{"m":0.31},"rx":{"m":0.27},"rxplus":{"m":0.25},"elite":{"m":0.23},"pro":{"m":0.22}}'::jsonb, NULL, '{"m":{"amrap":[200,600],"for_time":[200,1600],"emom":[100,200],"interval":[200,800]}}'::jsonb, NULL, NULL, 'mv_run', true, 2, '0.27 s/m = 4''30/km RX'),
  ('shuttle_run', 'Shuttle Run', 'run', ARRAY['mono']::text[], 'M', 'none', 'none', 'm', ARRAY['m']::text[], NULL, 6, 8, ARRAY[]::text[], '{"scaled":{"m":0.42},"inter":{"m":0.37},"rx":{"m":0.32},"rxplus":{"m":0.29},"elite":{"m":0.27},"pro":{"m":0.26}}'::jsonb, NULL, '{"m":{"amrap":[50,200],"for_time":[50,300],"emom":[40,80],"interval":[50,150]}}'::jsonb, NULL, NULL, NULL, true, 2, 'aller-retour 10 ou 25 m'),
  ('pull_up', 'Pull-ups', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 8, 3, ARRAY['rig']::text[], '{"scaled":{"reps":2.34},"inter":{"reps":2.07},"rx":{"reps":1.8},"rxplus":{"reps":1.66},"elite":{"reps":1.53},"pro":{"reps":1.44}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[9,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, '{"scaled":"ring_row","inter":"pull_up_banded"}'::jsonb, 'chest_to_bar', 'mv_pullup', true, 2, NULL),
  ('chest_to_bar', 'Chest-to-Bar', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 7, 1, ARRAY['rig']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, NULL, '{"reps":{"amrap":[6,12],"for_time":[9,21],"emom":[4,8],"interval":[5,10]}}'::jsonb, '{"scaled":"ring_row","inter":"pull_up"}'::jsonb, 'bar_muscle_up', 'mv_c2b', true, 2, NULL),
  ('toes_to_bar', 'Toes-to-Bar', 'gym', ARRAY['core', 'pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 8, 2, ARRAY['rig']::text[], '{"scaled":{"reps":2.6},"inter":{"reps":2.3},"rx":{"reps":2},"rxplus":{"reps":1.84},"elite":{"reps":1.7},"pro":{"reps":1.6}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,30],"emom":[5,10],"interval":[6,12]}}'::jsonb, '{"scaled":"hanging_knee_raise","inter":"toes_to_bar"}'::jsonb, NULL, 'mv_t2b', true, 2, NULL),
  ('bar_muscle_up', 'Bar Muscle-ups', 'gym', ARRAY['pull_v', 'push_v']::text[], 'G', 'high', 'high', 'reps', ARRAY['reps']::text[], NULL, 4, 0, ARRAY['rig']::text[], '{"scaled":{"reps":5.2},"inter":{"reps":4.6},"rx":{"reps":4},"rxplus":{"reps":3.68},"elite":{"reps":3.4},"pro":{"reps":3.2}}'::jsonb, NULL, '{"reps":{"amrap":[3,8],"for_time":[3,10],"emom":[2,5],"interval":[3,6]}}'::jsonb, '{"scaled":"pull_up_banded","inter":"chest_to_bar","rx":"chest_to_bar"}'::jsonb, NULL, 'mv_bmu', true, 2, NULL),
  ('ring_muscle_up', 'Ring Muscle-ups', 'gym', ARRAY['pull_v', 'push_v']::text[], 'G', 'high', 'high', 'reps', ARRAY['reps']::text[], NULL, 3, 0, ARRAY['rings']::text[], '{"scaled":{"reps":6.5},"inter":{"reps":5.75},"rx":{"reps":5},"rxplus":{"reps":4.6},"elite":{"reps":4.25},"pro":{"reps":4}}'::jsonb, NULL, '{"reps":{"amrap":[3,6],"for_time":[3,9],"emom":[2,4],"interval":[3,5]}}'::jsonb, '{"scaled":"ring_row","inter":"chest_to_bar","rx":"bar_muscle_up"}'::jsonb, NULL, 'mv_ring_mu', true, 2, NULL),
  ('handstand_push_up', 'Handstand Push-ups', 'gym', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 7, 1, ARRAY['wall']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, NULL, '{"reps":{"amrap":[6,12],"for_time":[9,21],"emom":[4,8],"interval":[5,10]}}'::jsonb, '{"scaled":"push_up","inter":"pike_push_up"}'::jsonb, 'strict_handstand_push_up', 'mv_hspu', true, 2, NULL),
  ('strict_handstand_push_up', 'Strict Handstand Push-Ups', 'gym', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 4, 0, ARRAY['wall']::text[], '{"scaled":{"reps":5.2},"inter":{"reps":4.6},"rx":{"reps":4},"rxplus":{"reps":3.68},"elite":{"reps":3.4},"pro":{"reps":3.2}}'::jsonb, NULL, '{"reps":{"amrap":[3,8],"for_time":[5,12],"emom":[2,5],"interval":[3,6]}}'::jsonb, '{"scaled":"push_up","inter":"pike_push_up","rx":"handstand_push_up"}'::jsonb, NULL, 'mv_hspu', true, 2, NULL),
  ('wall_walk', 'Wall Walk', 'gym', ARRAY['push_v', 'core']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 5, 1, ARRAY['wall']::text[], '{"scaled":{"reps":19.5},"inter":{"reps":17.25},"rx":{"reps":15},"rxplus":{"reps":13.8},"elite":{"reps":12.75},"pro":{"reps":12}}'::jsonb, NULL, '{"reps":{"amrap":[2,5],"for_time":[3,8],"emom":[1,3],"interval":[2,4]}}'::jsonb, '{"scaled":"inchworm","inter":"half_wall_walk"}'::jsonb, NULL, 'mv_wallwalk', true, 2, NULL),
  ('handstand_walk', 'Handstand Walk', 'gym', ARRAY['push_v', 'core']::text[], 'G', 'none', 'high', 'm', ARRAY['m']::text[], NULL, 4, 0, ARRAY['floor']::text[], '{"scaled":{"m":3.9},"inter":{"m":3.45},"rx":{"m":3},"rxplus":{"m":2.76},"elite":{"m":2.55},"pro":{"m":2.4}}'::jsonb, NULL, '{"m":{"amrap":[10,25],"for_time":[10,50],"emom":[5,15],"interval":[10,20]}}'::jsonb, '{"scaled":"bear_crawl","inter":"handstand_shoulder_tap"}'::jsonb, NULL, NULL, true, 2, NULL),
  ('ring_dip', 'Ring Dips', 'gym', ARRAY['push_v']::text[], 'G', 'low', 'high', 'reps', ARRAY['reps']::text[], NULL, 5, 0, ARRAY['rings']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, NULL, '{"reps":{"amrap":[6,12],"for_time":[9,21],"emom":[4,8],"interval":[5,10]}}'::jsonb, '{"scaled":"box_dip","inter":"ring_dip_banded"}'::jsonb, NULL, 'mv_ring_dip', true, 2, NULL),
  ('ring_row', 'Ring Rows', 'gym', ARRAY['pull_h']::text[], 'G', 'low', 'none', 'reps', ARRAY['reps']::text[], NULL, 3, 4, ARRAY['rings']::text[], '{"scaled":{"reps":2.6},"inter":{"reps":2.3},"rx":{"reps":2},"rxplus":{"reps":1.84},"elite":{"reps":1.7},"pro":{"reps":1.6}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,25],"emom":[6,12],"interval":[8,15]}}'::jsonb, NULL, NULL, 'mv_ring_row', true, 2, NULL),
  ('push_up', 'Push-ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 6, 5, ARRAY[]::text[], '{"scaled":{"reps":2.34},"inter":{"reps":2.07},"rx":{"reps":1.8},"rxplus":{"reps":1.66},"elite":{"reps":1.53},"pro":{"reps":1.44}}'::jsonb, NULL, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, '{"scaled":"knee_push_up"}'::jsonb, NULL, 'mv_pushup', true, 2, NULL),
  ('pistol', 'Pistols', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 4, 1, ARRAY[]::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, NULL, '{"reps":{"amrap":[6,12],"for_time":[8,20],"emom":[4,8],"interval":[5,10]}}'::jsonb, '{"scaled":"box_pistol","inter":"pistol_to_box"}'::jsonb, NULL, 'mv_pistol', true, 2, 'alterné, reps au total'),
  ('rope_climb', 'Rope Climbs', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 4, 0, ARRAY['rope']::text[], '{"scaled":{"reps":19.5},"inter":{"reps":17.25},"rx":{"reps":15},"rxplus":{"reps":13.8},"elite":{"reps":12.75},"pro":{"reps":12}}'::jsonb, NULL, '{"reps":{"amrap":[1,4],"for_time":[2,6],"emom":[1,2],"interval":[1,3]}}'::jsonb, '{"scaled":"rope_pull_from_floor","inter":"rope_climb"}'::jsonb, 'legless_rope_climb', NULL, true, 2, NULL),
  ('ghd_sit_up', 'GHD Sit-Ups', 'gym', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 5, 2, ARRAY['ghd']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, NULL, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,15]}}'::jsonb, '{"scaled":"sit_up","inter":"sit_up"}'::jsonb, NULL, NULL, true, 2, NULL),
  ('sit_up', 'Sit-ups', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 5, 5, ARRAY[]::text[], '{"scaled":{"reps":2.08},"inter":{"reps":1.84},"rx":{"reps":1.6},"rxplus":{"reps":1.47},"elite":{"reps":1.36},"pro":{"reps":1.28}}'::jsonb, NULL, '{"reps":{"amrap":[15,30],"for_time":[15,50],"emom":[10,20],"interval":[12,25]}}'::jsonb, NULL, NULL, 'mv_situp', true, 2, NULL),
  ('hollow_rock', 'Hollow Rocks', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 4, 5, ARRAY[]::text[], '{"scaled":{"reps":1.56},"inter":{"reps":1.38},"rx":{"reps":1.2},"rxplus":{"reps":1.1},"elite":{"reps":1.02},"pro":{"reps":0.96}}'::jsonb, NULL, '{"reps":{"amrap":[15,30],"for_time":[20,50],"emom":[10,20],"interval":[15,25]}}'::jsonb, NULL, NULL, 'mv_hollow', true, 2, NULL),
  ('plank_hold', 'Plank Hold', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 's', ARRAY['s']::text[], NULL, 3, 5, ARRAY[]::text[], '{"scaled":{"s":1.3},"inter":{"s":1.15},"rx":{"s":1},"rxplus":{"s":0.92},"elite":{"s":0.85},"pro":{"s":0.8}}'::jsonb, NULL, '{"s":{"amrap":[30,60],"for_time":[30,60],"emom":[30,45],"interval":[30,60]}}'::jsonb, NULL, NULL, NULL, true, 2, NULL),
  ('burpee', 'Burpees', 'bodyweight', ARRAY['core', 'mono']::text[], 'M', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 9, 7, ARRAY[]::text[], '{"scaled":{"reps":5.2},"inter":{"reps":4.6},"rx":{"reps":4},"rxplus":{"reps":3.68},"elite":{"reps":3.4},"pro":{"reps":3.2}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,30],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_burpee', true, 2, NULL),
  ('burpee_box_jump_over', 'Burpee Box Jump Over', 'bodyweight', ARRAY['core', 'mono']::text[], 'M', 'none', 'low', 'reps', ARRAY['reps']::text[], 'cm', 7, 4, ARRAY['box']::text[], '{"scaled":{"reps":7.8},"inter":{"reps":6.9},"rx":{"reps":6},"rxplus":{"reps":5.52},"elite":{"reps":5.1},"pro":{"reps":4.8}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[8,20],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_burpee_bj', true, 2, NULL),
  ('burpee_broad_jump', 'Burpee Broad Jumps', 'bodyweight', ARRAY['core', 'mono']::text[], 'M', 'none', 'low', 'm', ARRAY['m']::text[], NULL, 3, 10, ARRAY[]::text[], '{"scaled":{"m":3.38},"inter":{"m":2.99},"rx":{"m":2.6},"rxplus":{"m":2.39},"elite":{"m":2.21},"pro":{"m":2.08}}'::jsonb, NULL, '{"m":{"amrap":[20,50],"for_time":[20,80],"emom":[10,20],"interval":[15,30]}}'::jsonb, NULL, NULL, NULL, true, 2, 'Hyrox 80 m race'),
  ('box_jump', 'Box Jumps', 'box', ARRAY['squat', 'mono']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], 'cm', 8, 4, ARRAY['box']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,15]}}'::jsonb, '{"scaled":"box_step_up"}'::jsonb, NULL, 'mv_box_jump', true, 2, NULL),
  ('box_jump_over', 'Box Jump-overs', 'box', ARRAY['squat', 'mono']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], 'cm', 8, 4, ARRAY['box']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[10,30],"emom":[5,10],"interval":[6,12]}}'::jsonb, '{"scaled":"box_step_over"}'::jsonb, NULL, 'mv_box_jump', true, 2, NULL),
  ('box_step_up', 'Box Step-ups', 'box', ARRAY['lunge']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], 'cm', 4, 7, ARRAY['box']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,40],"emom":[8,15],"interval":[10,20]}}'::jsonb, NULL, NULL, 'mv_box_jump', true, 2, NULL),
  ('double_under', 'Double-unders', 'jump_rope', ARRAY['mono']::text[], 'M', 'low', 'none', 'reps', ARRAY['reps']::text[], NULL, 9, 3, ARRAY['jump_rope']::text[], '{"scaled":{"reps":0.72},"inter":{"reps":0.63},"rx":{"reps":0.55},"rxplus":{"reps":0.51},"elite":{"reps":0.47},"pro":{"reps":0.44}}'::jsonb, NULL, '{"reps":{"amrap":[30,60],"for_time":[50,100],"emom":[25,50],"interval":[30,60]}}'::jsonb, '{"scaled":"single_under","inter":"double_under"}'::jsonb, NULL, 'mv_du', true, 2, NULL),
  ('single_under', 'Single Unders', 'jump_rope', ARRAY['mono']::text[], 'M', 'low', 'none', 'reps', ARRAY['reps']::text[], NULL, 3, 2, ARRAY['jump_rope']::text[], '{"scaled":{"reps":0.45},"inter":{"reps":0.4},"rx":{"reps":0.35},"rxplus":{"reps":0.32},"elite":{"reps":0.3},"pro":{"reps":0.28}}'::jsonb, NULL, '{"reps":{"amrap":[60,120],"for_time":[100,200],"emom":[50,100],"interval":[60,120]}}'::jsonb, NULL, NULL, 'mv_su', true, 2, NULL),
  ('air_squat', 'Air Squats', 'bodyweight', ARRAY['squat']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 7, 4, ARRAY[]::text[], '{"scaled":{"reps":1.82},"inter":{"reps":1.61},"rx":{"reps":1.4},"rxplus":{"reps":1.29},"elite":{"reps":1.19},"pro":{"reps":1.12}}'::jsonb, NULL, '{"reps":{"amrap":[15,30],"for_time":[20,50],"emom":[10,20],"interval":[15,30]}}'::jsonb, NULL, NULL, 'mv_air_squat', true, 2, NULL),
  ('walking_lunge', 'Lunges', 'bodyweight', ARRAY['lunge']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 5, 5, ARRAY[]::text[], '{"scaled":{"reps":2.08},"inter":{"reps":1.84},"rx":{"reps":1.6},"rxplus":{"reps":1.47},"elite":{"reps":1.36},"pro":{"reps":1.28}}'::jsonb, NULL, '{"reps":{"amrap":[16,30],"for_time":[20,50],"emom":[12,20],"interval":[16,30]}}'::jsonb, NULL, NULL, 'mv_lunge', true, 2, NULL),
  ('cluster', 'Cluster', 'barbell', ARRAY['squat', 'hinge', 'push_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 6, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":5.85},"inter":{"reps":5.17},"rx":{"reps":4.5},"rxplus":{"reps":4.14},"elite":{"reps":3.82},"pro":{"reps":3.6}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[50,35]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[60,43]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[70,50]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[80,55]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[90,60]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[100,70]}}'::jsonb, '{"reps":{"amrap":[5,10],"for_time":[6,15],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, NULL, true, 2, 'squat clean + thruster'),
  ('hang_clean_and_jerk', 'Hang Clean & Jerk', 'barbell', ARRAY['hinge', 'push_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 6, 0, ARRAY['barbell']::text[], '{"scaled":{"reps":5.85},"inter":{"reps":5.17},"rx":{"reps":4.5},"rxplus":{"reps":4.14},"elite":{"reps":3.82},"pro":{"reps":3.6}}'::jsonb, '{"scaled":{"light":[30,20],"medium":[40,30],"heavy":[60,40]},"inter":{"light":[35,25],"medium":[50,35],"heavy":[80,55]},"rx":{"light":[43,30],"medium":[60,43],"heavy":[100,70]},"rxplus":{"light":[50,35],"medium":[70,50],"heavy":[120,80]},"elite":{"light":[55,40],"medium":[80,55],"heavy":[140,95]},"pro":{"light":[60,43],"medium":[90,60],"heavy":[160,110]}}'::jsonb, '{"reps":{"amrap":[4,10],"for_time":[5,12],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, 'mv_cj', true, 2, NULL),
  ('kb_snatch', 'KB Snatch', 'kettlebell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 6, 3, ARRAY['kettlebell']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, 'mv_kb_snatch', true, 2, 'alterné, reps au total'),
  ('kb_clean', 'KB Clean', 'kettlebell', ARRAY['hinge']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 4, 2, ARRAY['kettlebell']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, NULL, true, 2, 'alterné, reps au total'),
  ('kb_front_squat', 'KB Front Squat', 'kettlebell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 3, ARRAY['kettlebell']::text[], '{"scaled":{"reps":3.64},"inter":{"reps":3.22},"rx":{"reps":2.8},"rxplus":{"reps":2.58},"elite":{"reps":2.38},"pro":{"reps":2.24}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[10,20],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, NULL, true, 2, '2 KB, charge par main'),
  ('kb_clean_and_jerk', 'KB Clean & Jerk', 'kettlebell', ARRAY['hinge', 'push_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 5, 3, ARRAY['kettlebell']::text[], '{"scaled":{"reps":3.9},"inter":{"reps":3.45},"rx":{"reps":3},"rxplus":{"reps":2.76},"elite":{"reps":2.55},"pro":{"reps":2.4}}'::jsonb, '{"scaled":{"light":[12,8],"medium":[16,12],"heavy":[20,16]},"inter":{"light":[16,12],"medium":[20,16],"heavy":[24,16]},"rx":{"light":[20,16],"medium":[24,16],"heavy":[32,24]},"rxplus":{"light":[24,16],"medium":[28,20],"heavy":[32,24]},"elite":{"light":[24,20],"medium":[32,24],"heavy":[40,28]},"pro":{"light":[28,20],"medium":[32,24],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[8,20],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_kb_cj', true, 2, '2 KB ou alterné 1 KB'),
  ('kb_deadlift', 'KB Deadlift', 'kettlebell', ARRAY['hinge']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 4, 4, ARRAY['kettlebell']::text[], '{"scaled":{"reps":2.34},"inter":{"reps":2.07},"rx":{"reps":1.8},"rxplus":{"reps":1.66},"elite":{"reps":1.53},"pro":{"reps":1.44}}'::jsonb, '{"scaled":{"light":[16,12],"medium":[20,16],"heavy":[20,16]},"inter":{"light":[20,16],"medium":[24,16],"heavy":[24,16]},"rx":{"light":[24,16],"medium":[32,24],"heavy":[32,24]},"rxplus":{"light":[28,20],"medium":[32,24],"heavy":[32,24]},"elite":{"light":[32,24],"medium":[40,28],"heavy":[40,28]},"pro":{"light":[32,24],"medium":[40,28],"heavy":[40,28]}}'::jsonb, '{"reps":{"amrap":[10,20],"for_time":[15,30],"emom":[8,15],"interval":[10,20]}}'::jsonb, NULL, NULL, NULL, true, 2, '2 KB, charge par main'),
  ('box_jump_over_step_down', 'Box Jump Over Step Down', 'box', ARRAY['squat', 'mono']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], 'cm', 6, 4, ARRAY['box']::text[], '{"scaled":{"reps":4.42},"inter":{"reps":3.91},"rx":{"reps":3.4},"rxplus":{"reps":3.13},"elite":{"reps":2.89},"pro":{"reps":2.72}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[10,30],"emom":[5,10],"interval":[6,12]}}'::jsonb, '{"scaled":"box_step_over"}'::jsonb, NULL, NULL, true, 2, NULL),
  ('burpee_box_jump', 'Burpee Box Jump', 'bodyweight', ARRAY['core', 'mono']::text[], 'M', 'none', 'low', 'reps', ARRAY['reps']::text[], 'cm', 6, 4, ARRAY['box']::text[], '{"scaled":{"reps":7.15},"inter":{"reps":6.32},"rx":{"reps":5.5},"rxplus":{"reps":5.06},"elite":{"reps":4.67},"pro":{"reps":4.4}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[6,12],"for_time":[8,20],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, 'mv_burpee_bj', true, 2, NULL),
  ('burpee_over_the_bar', 'Burpees Over the Bar', 'bodyweight', ARRAY['core', 'mono']::text[], 'M', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 7, 2, ARRAY['barbell']::text[], '{"scaled":{"reps":5.46},"inter":{"reps":4.83},"rx":{"reps":4.2},"rxplus":{"reps":3.86},"elite":{"reps":3.57},"pro":{"reps":3.36}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, 'mv_burpee', true, 2, 'latéral'),
  ('pull_up_banded', 'Banded Pull-Ups', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['rig', 'band']::text[], '{"scaled":{"reps":2.6},"inter":{"reps":2.3},"rx":{"reps":2},"rxplus":{"reps":1.84},"elite":{"reps":1.7},"pro":{"reps":1.6}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('hanging_knee_raise', 'Hanging Knee Raises', 'gym', ARRAY['core', 'pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['rig']::text[], '{"scaled":{"reps":2.08},"inter":{"reps":1.84},"rx":{"reps":1.6},"rxplus":{"reps":1.47},"elite":{"reps":1.36},"pro":{"reps":1.28}}'::jsonb, NULL, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,15]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('legless_rope_climb', 'Legless Rope Climbs', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 0, ARRAY['rope']::text[], '{"scaled":{"reps":26},"inter":{"reps":23},"rx":{"reps":20},"rxplus":{"reps":18.4},"elite":{"reps":17},"pro":{"reps":16}}'::jsonb, NULL, '{"reps":{"amrap":[1,3],"for_time":[1,4],"emom":[1,1],"interval":[1,2]}}'::jsonb, NULL, NULL, NULL, true, 2, 'variante haute'),
  ('ring_dip_banded', 'Banded Ring Dips', 'gym', ARRAY['push_v']::text[], 'G', 'low', 'high', 'reps', ARRAY['reps']::text[], NULL, 2, 0, ARRAY['rings', 'band']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, NULL, '{"reps":{"amrap":[6,12],"for_time":[9,21],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('box_pistol', 'Box Pistols', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['box']::text[], '{"scaled":{"reps":3.25},"inter":{"reps":2.88},"rx":{"reps":2.5},"rxplus":{"reps":2.3},"elite":{"reps":2.12},"pro":{"reps":2}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,20],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('pistol_to_box', 'Pistols To Box', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['box']::text[], '{"scaled":{"reps":3.64},"inter":{"reps":3.22},"rx":{"reps":2.8},"rxplus":{"reps":2.58},"elite":{"reps":2.38},"pro":{"reps":2.24}}'::jsonb, NULL, '{"reps":{"amrap":[6,12],"for_time":[8,20],"emom":[4,8],"interval":[5,10]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('half_wall_walk', 'Half Wall Walks', 'gym', ARRAY['push_v', 'core']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['wall']::text[], '{"scaled":{"reps":13},"inter":{"reps":11.5},"rx":{"reps":10},"rxplus":{"reps":9.2},"elite":{"reps":8.5},"pro":{"reps":8}}'::jsonb, NULL, '{"reps":{"amrap":[3,6],"for_time":[4,10],"emom":[2,4],"interval":[3,5]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('pike_push_up', 'Pike Push-Ups', 'bodyweight', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 3, 2, ARRAY['box']::text[], '{"scaled":{"reps":2.86},"inter":{"reps":2.53},"rx":{"reps":2.2},"rxplus":{"reps":2.02},"elite":{"reps":1.87},"pro":{"reps":1.76}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,21],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution HSPU'),
  ('knee_push_up', 'Knee Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 2, ARRAY[]::text[], '{"scaled":{"reps":2.08},"inter":{"reps":1.84},"rx":{"reps":1.6},"rxplus":{"reps":1.47},"elite":{"reps":1.36},"pro":{"reps":1.28}}'::jsonb, NULL, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution'),
  ('bear_crawl', 'Bear Crawl', 'bodyweight', ARRAY['core', 'push_h']::text[], 'M', 'none', 'low', 'm', ARRAY['m']::text[], NULL, 2, 3, ARRAY[]::text[], '{"scaled":{"m":1.95},"inter":{"m":1.72},"rx":{"m":1.5},"rxplus":{"m":1.38},"elite":{"m":1.27},"pro":{"m":1.2}}'::jsonb, NULL, '{"m":{"amrap":[10,25],"for_time":[10,50],"emom":[10,20],"interval":[10,20]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution HS walk'),
  ('inchworm', 'Inchworms', 'bodyweight', ARRAY['core', 'push_h']::text[], 'M', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 2, ARRAY[]::text[], '{"scaled":{"reps":6.5},"inter":{"reps":5.75},"rx":{"reps":5},"rxplus":{"reps":4.6},"elite":{"reps":4.25},"pro":{"reps":4}}'::jsonb, NULL, '{"reps":{"amrap":[5,10],"for_time":[5,15],"emom":[3,6],"interval":[4,8]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution wall walk'),
  ('handstand_shoulder_tap', 'Handstand Shoulder Taps', 'gym', ARRAY['push_v', 'core']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 2, 0, ARRAY['wall']::text[], '{"scaled":{"reps":1.56},"inter":{"reps":1.38},"rx":{"reps":1.2},"rxplus":{"reps":1.1},"elite":{"reps":1.02},"pro":{"reps":0.96}}'::jsonb, NULL, '{"reps":{"amrap":[10,20],"for_time":[10,30],"emom":[6,12],"interval":[8,16]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution HS walk'),
  ('box_step_over', 'Box Step Over', 'box', ARRAY['lunge']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], 'cm', 3, 4, ARRAY['box']::text[], '{"scaled":{"reps":3.64},"inter":{"reps":3.22},"rx":{"reps":2.8},"rxplus":{"reps":2.58},"elite":{"reps":2.38},"pro":{"reps":2.24}}'::jsonb, '{"scaled":{"light":[50,40],"medium":[50,40],"heavy":[50,40]},"inter":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rx":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"rxplus":{"light":[60,50],"medium":[60,50],"heavy":[60,50]},"elite":{"light":[75,60],"medium":[75,60],"heavy":[75,60]},"pro":{"light":[75,60],"medium":[75,60],"heavy":[75,60]}}'::jsonb, '{"reps":{"amrap":[8,15],"for_time":[10,30],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution BJO'),
  ('rope_pull_from_floor', 'Rope Pulls From Floor', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 0, ARRAY['rope']::text[], '{"scaled":{"reps":7.8},"inter":{"reps":6.9},"rx":{"reps":6},"rxplus":{"reps":5.52},"elite":{"reps":5.1},"pro":{"reps":4.8}}'::jsonb, NULL, '{"reps":{"amrap":[3,6],"for_time":[3,10],"emom":[2,4],"interval":[2,5]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution rope climb'),
  ('box_dip', 'Box Dips', 'bodyweight', ARRAY['push_v']::text[], 'G', 'low', 'high', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['box']::text[], '{"scaled":{"reps":2.34},"inter":{"reps":2.07},"rx":{"reps":1.8},"rxplus":{"reps":1.66},"elite":{"reps":1.53},"pro":{"reps":1.44}}'::jsonb, NULL, '{"reps":{"amrap":[8,15],"for_time":[10,25],"emom":[5,10],"interval":[6,12]}}'::jsonb, NULL, NULL, NULL, true, 2, 'substitution ring dip'),
  ('back_rack_split_jerk', 'Back Rack Split Jerk', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_press', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('clean_pull', 'Clean Pull', 'barbell', ARRAY['hinge']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_clean_pull', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('db_deadlift', 'DB Deadlift', 'dumbbell', ARRAY['hinge']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, NULL, NULL, NULL, NULL, NULL, false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('db_push_press', 'DB Push Press', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_db_push_press', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('db_strict_press', 'DB Strict Press', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_db_strict_press', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('power_jerk', 'Power Jerk', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_press', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('snatch_balance', 'Snatch Balance', 'barbell', ARRAY['squat', 'push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_snatch_balance', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('snatch_high_pull', 'Snatch High Pull', 'barbell', ARRAY['hinge', 'pull_v']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_snatch_hp', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('split_jerk', 'Split Jerk', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_press', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('squat_clean_and_jerk', 'Squat Clean & Jerk', 'barbell', ARRAY['squat', 'hinge', 'push_v']::text[], 'W', 'high', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, NULL, false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('strict_press', 'Strict Press', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_strict_press', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('tall_clean', 'Tall Clean', 'barbell', ARRAY['squat']::text[], 'W', 'high', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_clean', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('v_ups', 'V-ups', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, NULL, NULL, NULL, NULL, 'mv_vup', false, 1, 'Ancien catalogue app — badges / back-office uniquement'),
  ('zercher_squat', 'Zercher Squat', 'barbell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, NULL, NULL, NULL, NULL, 'mv_squat', false, 1, 'Ancien catalogue app — badges / back-office uniquement')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, family = EXCLUDED.family, pattern = EXCLUDED.pattern, modality = EXCLUDED.modality,
  grip = EXCLUDED.grip, shoulder_load = EXCLUDED.shoulder_load, unit_default = EXCLUDED.unit_default,
  units_allowed = EXCLUDED.units_allowed, load_unit = EXCLUDED.load_unit, weight_functional = EXCLUDED.weight_functional,
  weight_hybrid = EXCLUDED.weight_hybrid, equipment = EXCLUDED.equipment, cadence = EXCLUDED.cadence, loads = EXCLUDED.loads,
  rep_ranges = EXCLUDED.rep_ranges, substitutions = EXCLUDED.substitutions, variant_up = EXCLUDED.variant_up,
  badge_key = EXCLUDED.badge_key, active = EXCLUDED.active, version = EXCLUDED.version, notes = EXCLUDED.notes,
  updated_at = now();


