-- ═════════════════════════════════════════════════════════════════════════════
-- Générateur Musculation V1 (M1) — colonnes musculation du catalogue.
--
-- FICHIER GÉNÉRÉ par packages/wod-engine/scripts/import-catalog.cjs depuis
-- packages/wod-engine/catalog/catalogue-musculation-v1.csv
-- (DDL : scripts/movement_catalog_muscu.ddl.sql). Ne pas éditer à la main.
--
-- Appliquée en prod : OUI (16/09/2026 19:41 UTC, dump `20260916T194119Z` dans le bucket privé `db-dumps`).
--
-- Additif et rejouable :
--   1. `movement_catalog` — familles `machine` / `cable` autorisées, colonnes
--      musculation (brief M1 §3). Les 18 exercices déjà présents dans le
--      catalogue metcon reçoivent les colonnes sur leur ligne (pas de doublon) ;
--      les nouveaux sont créés `active = true`, `weight_functional =
--      weight_hybrid = 0` (jamais tirés en metcon).
--   2. Aucune ligne metcon existante n'est modifiée en dehors des colonnes
--      musculation : `active` (tirage metcon) est conservé tel quel, les 14
--      lignes legacy inactives le restent (Strict Press compris : tirable en
--      musculation via ses colonnes muscu, jamais en metcon).
-- ═════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.movement_catalog DROP CONSTRAINT IF EXISTS movement_catalog_family_check;
ALTER TABLE public.movement_catalog ADD CONSTRAINT movement_catalog_family_check
  CHECK (family IN ('barbell','dumbbell','kettlebell','gym','bodyweight','erg','run','sled','carry','sandbag','wallball','jump_rope','box','machine','cable','other'));

ALTER TABLE public.movement_catalog
  ADD COLUMN IF NOT EXISTS discipline_muscu  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS muscle_primary    text
    CHECK (muscle_primary IS NULL OR muscle_primary IN ('pecs','epaules','epaules_ant','epaules_post','triceps','dos','lombaires','biceps','quadriceps','ischios','fessiers','mollets','tronc','trapezes','avant_bras','obliques','coiffe')),
  ADD COLUMN IF NOT EXISTS muscle_secondary  text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS compound          boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS unilateral        boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS level_min         text CHECK (level_min IS NULL OR level_min IN ('debutant','inter','avance')),
  ADD COLUMN IF NOT EXISTS load_mode         text CHECK (load_mode IS NULL OR load_mode IN ('1rm','rpe','bodyweight')),
  ADD COLUMN IF NOT EXISTS rm_reference      text CHECK (rm_reference IS NULL OR rm_reference IN ('back_squat','deadlift','bench','press','hip_thrust')),
  ADD COLUMN IF NOT EXISTS rm_factor         numeric(4,2) CHECK (rm_factor IS NULL OR rm_factor > 0),
  ADD COLUMN IF NOT EXISTS seconds_per_rep   numeric(4,1) CHECK (seconds_per_rep IS NULL OR seconds_per_rep > 0),
  ADD COLUMN IF NOT EXISTS setup_s           integer CHECK (setup_s IS NULL OR setup_s >= 0),
  ADD COLUMN IF NOT EXISTS objectives        text[] NOT NULL DEFAULT '{}'
    CHECK (objectives <@ ARRAY['hypertrophie','force','endurance']::text[]),
  -- {"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]} — reps, secondes (gainage) ou mètres (carry)
  ADD COLUMN IF NOT EXISTS rep_ranges_muscu  jsonb,
  ADD COLUMN IF NOT EXISTS weight_bodyweight smallint NOT NULL DEFAULT 0 CHECK (weight_bodyweight BETWEEN 0 AND 10),
  ADD COLUMN IF NOT EXISTS weight_box        smallint NOT NULL DEFAULT 0 CHECK (weight_box BETWEEN 0 AND 10),
  ADD COLUMN IF NOT EXISTS weight_gym        smallint NOT NULL DEFAULT 0 CHECK (weight_gym BETWEEN 0 AND 10),
  ADD COLUMN IF NOT EXISTS muscu_unit        text NOT NULL DEFAULT 'reps' CHECK (muscu_unit IN ('reps','s','m')),
  -- 1 = meilleur exercice principal pour le muscle (slot main_compound), 5 = dernier recours
  ADD COLUMN IF NOT EXISTS priority          smallint CHECK (priority IS NULL OR priority BETWEEN 1 AND 5),
  -- geste : un seul exercice par groupe et par séance (sauf Full body, sauf paire compound + isolation explicite)
  ADD COLUMN IF NOT EXISTS movement_group    text
    CHECK (movement_group IS NULL OR movement_group IN ('press_h','press_v','pull_v','row','squat','hinge','lunge','hip_ext','curl','triceps_ext','fly','raise','shrug','core_flex','core_anti','carry'));

ALTER TABLE public.movement_catalog DROP CONSTRAINT IF EXISTS movement_catalog_muscu_coherent;
ALTER TABLE public.movement_catalog ADD CONSTRAINT movement_catalog_muscu_coherent CHECK (
  NOT discipline_muscu OR (
    muscle_primary IS NOT NULL AND level_min IS NOT NULL AND load_mode IS NOT NULL
    AND seconds_per_rep IS NOT NULL AND setup_s IS NOT NULL
    AND cardinality(objectives) > 0 AND rep_ranges_muscu IS NOT NULL
    AND (load_mode <> '1rm' OR (rm_reference IS NOT NULL AND rm_factor IS NOT NULL))
    AND (weight_bodyweight + weight_box + weight_gym) > 0
    AND priority IS NOT NULL AND movement_group IS NOT NULL
  )
);

COMMENT ON COLUMN public.movement_catalog.discipline_muscu IS
  'Tirable par le générateur Musculation (brief M1). Les colonnes muscle_primary … muscu_unit ne sont renseignées que pour ces lignes.';
COMMENT ON COLUMN public.movement_catalog.rep_ranges_muscu IS
  'Plages par objectif : {"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]} — en reps, secondes (muscu_unit = s) ou mètres (m).';
COMMENT ON COLUMN public.movement_catalog.rm_factor IS
  'Charge = 1RM(rm_reference) × rm_factor × % de l''objectif, arrondi à 2,5 kg (load_mode = 1rm).';

CREATE INDEX IF NOT EXISTS idx_movement_catalog_muscu
  ON public.movement_catalog (muscle_primary) WHERE discipline_muscu;

-- ── Seed : catalogue-musculation-v1 (179 exercices, dont 19 déjà présents : colonnes ajoutées sur la ligne existante) ──
-- Sur conflit d'id, seules les colonnes musculation sont écrites : les colonnes metcon de prod (dont active, drapeau metcon) restent intactes.
-- Le moteur musculation ne lit pas active : un exercice se retire de la musculation par ses poids weight_* à 0.
INSERT INTO public.movement_catalog
  (id, name, family, pattern, modality, grip, shoulder_load, unit_default, units_allowed,
   load_unit, weight_functional, weight_hybrid, equipment, badge_key, active, version, notes,
   discipline_muscu, muscle_primary, muscle_secondary, compound, unilateral, level_min,
   load_mode, rm_reference, rm_factor, seconds_per_rep, setup_s,
   objectives, rep_ranges_muscu, weight_bodyweight, weight_box, weight_gym, muscu_unit,
   priority, movement_group)
VALUES
  ('front_squat', 'Front Squat', 'barbell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 7, 1, ARRAY['barbell']::text[], 'mv_squat', true, 2, NULL, true, 'quadriceps', ARRAY['tronc', 'fessiers']::text[], true, false, 'inter', '1rm', 'back_squat', 0.85, 4, 60, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 2, 'squat'),
  ('back_squat', 'Back Squat', 'barbell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 1, ARRAY['barbell', 'rack']::text[], 'mv_squat', true, 2, NULL, true, 'quadriceps', ARRAY['fessiers', 'tronc']::text[], true, false, 'debutant', '1rm', 'back_squat', 1, 4, 60, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'squat'),
  ('deadlift', 'Deadlift', 'barbell', ARRAY['hinge']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 9, 2, ARRAY['barbell']::text[], 'mv_deadlifts', true, 2, 'bench 21-15-9 = Diane', true, 'dos', ARRAY['ischios', 'fessiers', 'tronc']::text[], true, false, 'debutant', '1rm', 'deadlift', 1, 3, 45, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 4, 'hinge'),
  ('bench_press', 'Bench Press', 'barbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 4, 0, ARRAY['barbell', 'bench']::text[], 'mv_bench_press', true, 2, NULL, true, 'pecs', ARRAY['triceps', 'epaules_ant']::text[], true, false, 'debutant', '1rm', 'bench', 1, 3, 45, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'press_h'),
  ('kb_goblet_squat', 'Goblet Squat', 'kettlebell', ARRAY['squat']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 5, 4, ARRAY['kettlebell']::text[], 'mv_goblet_squat', true, 2, NULL, true, 'quadriceps', ARRAY['fessiers']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'squat'),
  ('db_lunge', 'DB Lunges', 'dumbbell', ARRAY['lunge']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 6, 7, ARRAY['dumbbell']::text[], 'mv_lunge', true, 2, 'reps = pas au total', true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'lunge'),
  ('db_farmer_carry', 'Farmer Carry', 'carry', ARRAY['carry']::text[], 'W', 'high', 'none', 'm', ARRAY['m']::text[], 'kg', 4, 9, ARRAY['kettlebell', 'dumbbell']::text[], NULL, true, 2, 'charge par main', true, 'tronc', ARRAY['avant_bras', 'trapezes']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 1, 20, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 8, 8, 'm', 3, 'carry'),
  ('handstand_push_up', 'Handstand Push-ups', 'gym', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 7, 1, ARRAY['wall']::text[], 'mv_hspu', true, 2, NULL, true, 'epaules', ARRAY['triceps']::text[], true, false, 'avance', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 6, 0, 8, 'reps', 5, 'press_v'),
  ('ring_row', 'Ring Rows', 'gym', ARRAY['pull_h']::text[], 'G', 'low', 'none', 'reps', ARRAY['reps']::text[], NULL, 3, 4, ARRAY['rings']::text[], 'mv_ring_row', true, 2, NULL, true, 'dos', ARRAY['biceps', 'trapezes']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'row'),
  ('push_up', 'Push-ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 6, 5, ARRAY[]::text[], 'mv_pushup', true, 2, NULL, true, 'pecs', ARRAY['triceps', 'tronc']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 5, 'press_h'),
  ('pistol', 'Pistols', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 4, 1, ARRAY[]::text[], 'mv_pistol', true, 2, 'alterné, reps au total', true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'avance', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 6, 8, 8, 'reps', 5, 'squat'),
  ('plank_hold', 'Plank Hold', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'low', 's', ARRAY['s']::text[], NULL, 3, 5, ARRAY[]::text[], NULL, true, 2, NULL, true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 's', 3, 'core_anti'),
  ('box_step_up', 'Box Step-ups', 'box', ARRAY['lunge']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], 'cm', 4, 7, ARRAY['box']::text[], 'mv_box_jump', true, 2, NULL, true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'lunge'),
  ('air_squat', 'Air Squats', 'bodyweight', ARRAY['squat']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 7, 4, ARRAY[]::text[], 'mv_air_squat', true, 2, NULL, true, 'quadriceps', ARRAY['fessiers']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 5, 'squat'),
  ('walking_lunge', 'Lunges', 'bodyweight', ARRAY['lunge']::text[], 'M', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 5, 5, ARRAY[]::text[], 'mv_lunge', true, 2, NULL, true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 5, 'lunge'),
  ('pull_up_banded', 'Banded Pull-Ups', 'gym', ARRAY['pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['rig', 'band']::text[], NULL, true, 2, 'substitution', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[12,15]}'::jsonb, 0, 6, 4, 'reps', 2, 'pull_v'),
  ('hanging_knee_raise', 'Hanging Knee Raises', 'gym', ARRAY['core', 'pull_v']::text[], 'G', 'high', 'low', 'reps', ARRAY['reps']::text[], NULL, 2, 1, ARRAY['rig']::text[], NULL, true, 2, 'substitution', true, 'tronc', ARRAY['hip_flexors']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('pike_push_up', 'Pike Push-Ups', 'bodyweight', ARRAY['push_v']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 3, 2, ARRAY['box']::text[], NULL, true, 2, 'substitution HSPU', true, 'epaules', ARRAY['triceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 5, 'press_v'),
  ('strict_press', 'Strict Press', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], 'mv_strict_press', true, 1, 'Ancien catalogue app — badges / back-office uniquement', true, 'epaules', ARRAY['triceps', 'tronc']::text[], true, false, 'debutant', '1rm', 'press', 1, 3, 45, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'press_v'),
  ('incline_bench_press', 'Incline Bench Press', 'barbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'bench_incline', 'rack']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['epaules_ant', 'triceps']::text[], true, false, 'inter', '1rm', 'bench', 0.8, 3, 45, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 2, 'press_h'),
  ('db_bench_press', 'DB Bench Press', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['triceps', 'epaules_ant']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 3, 'press_h'),
  ('incline_db_press', 'Incline DB Press', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench_incline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['epaules_ant', 'triceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 3, 'press_h'),
  ('machine_chest_press', 'Machine Chest Press', 'machine', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['chest_press_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['triceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 4, 'press_h'),
  ('cable_fly', 'Cable Fly', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('pec_deck', 'Pec Deck', 'machine', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['pec_deck']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('db_fly', 'DB Fly', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'fly'),
  ('dips', 'Dips', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['dip_station']::text[], NULL, true, 1, 'Musculation — lesté possible en force', true, 'pecs', ARRAY['triceps', 'epaules_ant']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 4, 'press_h'),
  ('db_shoulder_press', 'DB Shoulder Press', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], 'mv_db_strict_press', true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY['triceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 2, 'press_v'),
  ('arnold_press', 'Arnold Press', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY['triceps']::text[], true, false, 'inter', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 8, 8, 'reps', 3, 'press_v'),
  ('lateral_raise', 'Lateral Raise', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'raise'),
  ('cable_lateral_raise', 'Cable Lateral Raise', 'cable', ARRAY['push_v']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'raise'),
  ('rear_delt_fly', 'Rear Delt Fly', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_post', ARRAY['haut_dos']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'fly'),
  ('face_pull', 'Face Pull', 'cable', ARRAY['pull_h']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_post', ARRAY['haut_dos']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('front_raise', 'Front Raise', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_ant', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'raise'),
  ('landmine_press', 'Landmine Press', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'landmine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY['pecs', 'tronc']::text[], true, true, 'inter', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 8, 8, 'reps', 4, 'press_v'),
  ('cable_triceps_pushdown', 'Triceps Pushdown', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('overhead_triceps_extension', 'Overhead Triceps Extension', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'triceps_ext'),
  ('skull_crusher', 'Skull Crushers', 'barbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'triceps_ext'),
  ('close_grip_bench', 'Close Grip Bench Press', 'barbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'bench', 'rack']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY['pecs']::text[], true, false, 'inter', '1rm', 'bench', 0.85, 3, 45, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 1, 'press_h'),
  ('bench_dip', 'Bench Dips', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'press_h'),
  ('barbell_row', 'Barbell Row', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps', 'epaules_post']::text[], true, false, 'debutant', '1rm', 'deadlift', 0.5, 3, 30, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 3, 'row'),
  ('pendlay_row', 'Pendlay Row', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', '1rm', 'deadlift', 0.5, 3, 30, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 3, 'row'),
  ('db_row', 'DB Row', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 4, 'row'),
  ('lat_pulldown', 'Lat Pulldown', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['lat_pulldown']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 2, 'pull_v'),
  ('seated_cable_row', 'Seated Cable Row', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable_row']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps', 'epaules_post']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 4, 'row'),
  ('chest_supported_row', 'Chest Supported Row', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench_incline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps', 'epaules_post']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 25, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 4, 'row'),
  ('t_bar_row', 'T-Bar Row', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'landmine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 4, 'row'),
  ('machine_row', 'Machine Row', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['row_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 4, 'row'),
  ('strict_pull_up', 'Strict Pull-Ups', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], 'mv_pullup', true, 1, 'Musculation — lesté possible en force ; sub débutant : lat pulldown ou banded', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'pull_v'),
  ('chin_up', 'Chin-Ups', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'pull_v'),
  ('straight_arm_pulldown', 'Straight Arm Pulldown', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'pull_v'),
  ('rack_pull', 'Rack Pull', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'rack']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['ischios', 'fessiers']::text[], true, false, 'inter', '1rm', 'deadlift', 1.1, 3, 60, ARRAY['force']::text[], '{"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 5, 'hinge'),
  ('back_extension', 'Back Extension', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['ghd']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'lombaires', ARRAY['fessiers', 'ischios']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'hinge'),
  ('barbell_curl', 'Barbell Curl', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('db_curl', 'DB Curl', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('hammer_curl', 'Hammer Curl', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY['avant_bras']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('incline_db_curl', 'Incline DB Curl', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench_incline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('cable_curl', 'Cable Curl', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('preacher_curl', 'Preacher Curl', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['preacher_bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('leg_press', 'Leg Press', 'machine', ARRAY['squat']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['leg_press']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'quadriceps', ARRAY['fessiers']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 40, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 3, 'squat'),
  ('hack_squat', 'Hack Squat', 'machine', ARRAY['squat']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['hack_squat']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'quadriceps', ARRAY['fessiers']::text[], true, false, 'inter', 'rpe', NULL, NULL, 3, 40, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 0, 8, 'reps', 4, 'squat'),
  ('bulgarian_split_squat', 'Bulgarian Split Squat', 'dumbbell', ARRAY['squat']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'quadriceps', ARRAY['fessiers']::text[], true, true, 'inter', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'lunge'),
  ('romanian_deadlift', 'Romanian Deadlift', 'barbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'ischios', ARRAY['fessiers', 'lombaires']::text[], true, false, 'debutant', '1rm', 'deadlift', 0.7, 4, 30, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'hinge'),
  ('db_rdl', 'DB Romanian Deadlift', 'dumbbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'ischios', ARRAY['fessiers']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 4, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 3, 'hinge'),
  ('leg_extension', 'Leg Extension', 'machine', ARRAY['squat']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['leg_extension']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'quadriceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'squat'),
  ('leg_curl', 'Leg Curl', 'machine', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['leg_curl']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'ischios', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 2, 'curl'),
  ('hip_thrust', 'Hip Thrust', 'barbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios']::text[], true, false, 'debutant', '1rm', 'hip_thrust', 1, 3, 60, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'hip_ext'),
  ('glute_bridge', 'Glute Bridge', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — à deux jambes ; variante facile sans matériel', true, 'fessiers', ARRAY['ischios']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,15],"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'hip_ext'),
  ('good_morning', 'Good Morning', 'barbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'rack']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'ischios', ARRAY['lombaires']::text[], true, false, 'inter', 'rpe', NULL, NULL, 4, 30, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 8, 8, 'reps', 4, 'hinge'),
  ('sumo_deadlift', 'Sumo Deadlift', 'barbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios', 'quadriceps']::text[], true, false, 'inter', '1rm', 'deadlift', 1, 3, 45, ARRAY['force', 'hypertrophie']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 4, 'hinge'),
  ('standing_calf_raise', 'Standing Calf Raise', 'machine', ARRAY['mono']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['calf_machine', 'dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'mollets', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'raise'),
  ('seated_calf_raise', 'Seated Calf Raise', 'machine', ARRAY['mono']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['calf_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'mollets', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'raise'),
  ('nordic_curl', 'Nordic Curl', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'ischios', ARRAY[]::text[], false, false, 'avance', 'bodyweight', NULL, NULL, 5, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 4, 'curl'),
  ('hanging_leg_raise', 'Hanging Leg Raise', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY['hip_flexors']::text[], false, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('cable_crunch', 'Cable Crunch', 'cable', ARRAY['core']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'core_flex'),
  ('ab_wheel', 'Ab Wheel Rollout', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['ab_wheel']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY['lats']::text[], false, false, 'inter', 'bodyweight', NULL, NULL, 4, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_anti'),
  ('pallof_press', 'Pallof Press', 'cable', ARRAY['core']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable', 'band']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'core_anti'),
  ('dead_bug', 'Dead Bug', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_anti'),
  ('side_plank', 'Side Plank', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — unité secondes', true, 'tronc', ARRAY[]::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 's', 3, 'core_anti'),
  ('russian_twist', 'Russian Twist', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['wallball', 'dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY['obliques']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 1, 10, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('suitcase_carry', 'Suitcase Carry', 'carry', ARRAY['core']::text[], 'W', 'low', 'none', 'm', ARRAY['m']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'kettlebell']::text[], NULL, true, 1, 'Musculation — unité mètres', true, 'tronc', ARRAY['obliques']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 1, 20, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 8, 8, 'm', 3, 'carry'),
  ('decline_bench_press', 'Decline Bench Press', 'barbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'bench_decline', 'rack']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['triceps']::text[], true, false, 'inter', '1rm', 'bench', 1.05, 3, 45, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 0, 8, 'reps', 3, 'press_h'),
  ('decline_db_press', 'Decline DB Press', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench_decline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['triceps']::text[], true, false, 'inter', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 0, 8, 'reps', 4, 'press_h'),
  ('machine_incline_press', 'Machine Incline Press', 'machine', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['chest_press_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['epaules_ant', 'triceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 4, 'press_h'),
  ('db_pullover', 'DB Pullover', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['dos', 'triceps']::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'pull_v'),
  ('cable_pullover', 'Cable Pullover', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['dos']::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'pull_v'),
  ('incline_db_fly', 'Incline DB Fly', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench_incline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'fly'),
  ('low_cable_fly', 'Low To High Cable Fly', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['epaules_ant']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('wide_push_up', 'Wide Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['triceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 5, 'press_h'),
  ('decline_push_up', 'Decline Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['box']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'pecs', ARRAY['epaules_ant', 'triceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'press_h'),
  ('machine_shoulder_press', 'Machine Shoulder Press', 'machine', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['shoulder_press_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY['triceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 3, 'press_v'),
  ('behind_neck_press', 'Behind The Neck Press', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'rack']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY['triceps']::text[], true, false, 'avance', '1rm', 'press', 0.85, 3, 45, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 8, 8, 'reps', 4, 'press_v'),
  ('upright_row', 'Upright Row', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY['trapezes']::text[], true, false, 'inter', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 5, 'raise'),
  ('bent_over_lateral_raise', 'Bent Over Lateral Raise', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_post', ARRAY['haut_dos']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'fly'),
  ('one_arm_incline_lateral_raise', 'Incline One-Arm Lateral Raise', 'dumbbell', ARRAY['push_v']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench_incline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules', ARRAY[]::text[], false, true, 'avance', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'raise'),
  ('rear_delt_machine', 'Rear Delt Machine', 'machine', ARRAY['pull_h']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['pec_deck']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_post', ARRAY['haut_dos']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('barbell_front_raise', 'Barbell Front Raise', 'barbell', ARRAY['push_v']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_ant', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'raise'),
  ('cable_front_raise', 'Cable Front Raise', 'cable', ARRAY['push_v']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'epaules_ant', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'raise'),
  ('external_rotation', 'External Rotation (L-Fly)', 'cable', ARRAY['pull_h']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable', 'band', 'dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'coiffe', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('internal_rotation', 'Internal Rotation', 'cable', ARRAY['pull_h']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable', 'band']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'coiffe', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'fly'),
  ('yates_row', 'Yates Row', 'barbell', ARRAY['pull_v']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'trapezes', ARRAY['dos', 'biceps']::text[], true, false, 'inter', '1rm', 'deadlift', 0.5, 3, 30, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 3, 'row'),
  ('supinated_barbell_row', 'Supinated Barbell Row', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps', 'trapezes']::text[], true, false, 'inter', '1rm', 'deadlift', 0.45, 3, 30, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 8, 8, 'reps', 3, 'row'),
  ('one_arm_machine_row', 'One-Arm Machine Row', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['row_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 5, 'row'),
  ('one_arm_cable_row', 'One-Arm Cable Row', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable_row']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 5, 'row'),
  ('barbell_shrug', 'Barbell Shrug', 'barbell', ARRAY['pull_v']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'trapezes', ARRAY[]::text[], false, false, 'debutant', '1rm', 'deadlift', 0.6, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'shrug'),
  ('db_shrug', 'DB Shrug', 'dumbbell', ARRAY['pull_v']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'trapezes', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'shrug'),
  ('machine_shrug', 'Machine Shrug', 'machine', ARRAY['pull_v']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['shrug_machine', 'calf_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'trapezes', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'shrug'),
  ('cable_shrug', 'Cable Shrug', 'cable', ARRAY['pull_v']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'trapezes', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'shrug'),
  ('wide_grip_pull_up', 'Wide Grip Pull-Ups', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 1, 'pull_v'),
  ('neutral_grip_pull_up', 'Neutral Grip Pull-Ups', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'pull_v'),
  ('close_grip_pull_up', 'Close Grip Pull-Ups', 'bodyweight', ARRAY['pull_h']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 1, 'pull_v'),
  ('machine_pullover', 'Machine Pullover', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['pullover_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['pecs']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'pull_v'),
  ('converging_pulldown', 'Converging Machine Pulldown', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['lat_pulldown']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 2, 'pull_v'),
  ('one_arm_pulldown', 'One-Arm Lat Pulldown', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 2, 'pull_v'),
  ('close_grip_pulldown', 'Close Grip Lat Pulldown', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['lat_pulldown']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 2, 'pull_v'),
  ('supinated_pulldown', 'Supinated Lat Pulldown', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['lat_pulldown']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'dos', ARRAY['biceps']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 2, 'pull_v'),
  ('low_cable_skull_crusher', 'Lying Cable Triceps Extension', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 25, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('machine_dips', 'Machine Dips', 'machine', ARRAY['push_h']::text[], 'W', 'low', 'high', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dip_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY['pecs']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 3, 'press_h'),
  ('close_grip_dips', 'Close Grip Dips', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['dip_station']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY['pecs']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'force']::text[], '{"hypertrophie":[8,12],"force":[3,5]}'::jsonb, 0, 8, 8, 'reps', 2, 'press_h'),
  ('wall_triceps_extension', 'Wall Triceps Extension', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'low', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'triceps_ext'),
  ('cable_overhead_extension', 'Cable Overhead Triceps Extension', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('one_arm_overhead_extension', 'One-Arm Overhead Triceps Extension', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, true, 'inter', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'triceps_ext'),
  ('machine_triceps_extension', 'Machine Triceps Extension', 'machine', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['triceps_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('diamond_push_up', 'Diamond Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY['pecs']::text[], true, false, 'inter', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 4, 'press_h'),
  ('tate_press', 'Tate Press', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'avance', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'triceps_ext'),
  ('rope_pushdown', 'Rope Triceps Pushdown', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('one_arm_pushdown', 'One-Arm Triceps Pushdown', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('reverse_grip_pushdown', 'Reverse Grip Pushdown', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('db_kickback', 'DB Kickback', 'dumbbell', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'triceps_ext'),
  ('cable_kickback', 'Cable Kickback', 'cable', ARRAY['push_h']::text[], 'W', 'low', 'low', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'triceps', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'triceps_ext'),
  ('preacher_barbell_curl', 'Preacher Barbell Curl', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'preacher_bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('cross_body_hammer_curl', 'Cross-Body Hammer Curl', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY['avant_bras']::text[], false, true, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('lying_cable_curl', 'Lying Cable Curl', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 25, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('spider_curl', 'Spider Curl', 'barbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'dumbbell', 'bench_incline']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('rope_hammer_curl', 'Rope Hammer Curl', 'cable', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY['avant_bras']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('machine_preacher_curl', 'Machine Preacher Curl', 'machine', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['preacher_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('concentration_curl', 'Concentration Curl', 'dumbbell', ARRAY['pull_h']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'biceps', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'curl'),
  ('reverse_curl', 'Reverse Curl', 'barbell', ARRAY['carry']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'avant_bras', ARRAY['biceps']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'curl'),
  ('wrist_curl', 'Wrist Curl', 'barbell', ARRAY['carry']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'avant_bras', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'carry'),
  ('wrist_extension', 'Wrist Extension', 'barbell', ARRAY['carry']::text[], 'W', 'high', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['barbell', 'dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'avant_bras', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'carry'),
  ('wrist_roller', 'Wrist Roller', 'other', ARRAY['carry']::text[], 'W', 'high', 'none', 's', ARRAY['s']::text[], 'kg', 0, 0, ARRAY['wrist_roller']::text[], NULL, true, 1, 'Musculation — unité secondes', true, 'avant_bras', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 1, 20, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 0, 6, 's', 3, 'carry'),
  ('abmat_crunch', 'AbMat Crunch', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['abmat']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 0, 6, 'reps', 3, 'core_flex'),
  ('floor_crunch', 'Crunch', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_flex'),
  ('reverse_crunch', 'Reverse Crunch', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY['hip_flexors']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_flex'),
  ('machine_crunch', 'Machine Crunch', 'machine', ARRAY['core']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['ab_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'core_flex'),
  ('swiss_ball_crunch', 'Swiss Ball Crunch', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['swiss_ball']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'core_flex'),
  ('oblique_crunch', 'Oblique Crunch', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY[]::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_flex'),
  ('hanging_oblique_raise', 'Hanging Oblique Knee Raise', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['rig']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY['hip_flexors']::text[], false, true, 'inter', 'bodyweight', NULL, NULL, 2, 10, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('rotation_machine', 'Torso Rotation Machine', 'machine', ARRAY['core']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['rotation_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'core_flex'),
  ('vacuum', 'Stomach Vacuum', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — unité secondes', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 's', 3, 'core_anti'),
  ('crunch_with_rotation', 'Crunch With Rotation', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_flex'),
  ('dragon_flag', 'Dragon Flag', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY[]::text[], false, false, 'avance', 'bodyweight', NULL, NULL, 5, 15, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('db_side_bend', 'DB Side Bend', 'dumbbell', ARRAY['core']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 10, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('standing_rotation', 'Standing Broomstick Rotation', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['pvc']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 0, 6, 'reps', 3, 'core_flex'),
  ('oblique_bench_raise', 'Oblique Raise On Roman Chair', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['ghd']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'obliques', ARRAY['lombaires']::text[], false, true, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 0, 6, 6, 'reps', 3, 'core_flex'),
  ('wall_sit', 'Wall Sit', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'none', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY['wall']::text[], NULL, true, 1, 'Musculation — unité secondes', true, 'quadriceps', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 0, 6, 's', 3, 'squat'),
  ('single_leg_glute_bridge', 'Single-Leg Glute Bridge', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios']::text[], false, true, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'hip_ext'),
  ('bodyweight_single_leg_rdl', 'Single-Leg RDL (bodyweight)', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'ischios', ARRAY['fessiers', 'tronc']::text[], true, true, 'inter', 'bodyweight', NULL, NULL, 4, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 8, 8, 'reps', 5, 'hinge'),
  ('bodyweight_calf_raise', 'Calf Raise (bodyweight)', 'bodyweight', ARRAY['mono']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'mollets', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'raise'),
  ('superman', 'Superman Hold', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — unité secondes', true, 'lombaires', ARRAY['fessiers']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 's', 3, 'core_anti'),
  ('hollow_hold', 'Hollow Hold', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — unité secondes', true, 'tronc', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 's', 3, 'core_anti'),
  ('mountain_climber', 'Mountain Climbers', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], 'mv_mtclimber', true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'tronc', ARRAY['hip_flexors']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_flex'),
  ('cable_pull_through', 'Cable Pull-Through', 'cable', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios']::text[], false, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'hip_ext'),
  ('hip_abduction_machine', 'Hip Abduction Machine', 'machine', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['abduction_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY[]::text[], false, false, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'hip_ext'),
  ('cable_hip_abduction', 'Cable Hip Abduction', 'cable', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'hip_ext'),
  ('banded_hip_abduction', 'Banded Hip Abduction', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['band']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'hip_ext'),
  ('glute_kickback', 'Glute Kickback (câble)', 'cable', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['cable']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY[]::text[], false, true, 'debutant', 'rpe', NULL, NULL, 2, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 0, 6, 'reps', 3, 'hip_ext'),
  ('db_sumo_squat', 'DB Sumo Squat', 'dumbbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'kettlebell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['quadriceps', 'adducteurs']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'squat'),
  ('frog_pump', 'Frog Pump', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY[]::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 'reps', 3, 'hip_ext'),
  ('db_hip_thrust', 'DB Hip Thrust', 'dumbbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell', 'bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 3, 'hip_ext'),
  ('single_leg_hip_thrust', 'Single-Leg Hip Thrust', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['bench']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios']::text[], true, true, 'inter', 'bodyweight', NULL, NULL, 3, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'hip_ext'),
  ('reverse_lunge', 'DB Reverse Lunge', 'dumbbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['quadriceps']::text[], true, true, 'debutant', 'rpe', NULL, NULL, 2, 15, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 0, 8, 8, 'reps', 5, 'lunge'),
  ('step_up_high', 'High Box Step-Up', 'dumbbell', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['box', 'dumbbell']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['quadriceps']::text[], true, true, 'inter', 'rpe', NULL, NULL, 3, 20, ARRAY['hypertrophie']::text[], '{"hypertrophie":[8,12]}'::jsonb, 0, 8, 8, 'reps', 5, 'lunge'),
  ('hip_thrust_machine', 'Hip Thrust Machine', 'machine', ARRAY['hinge']::text[], 'W', 'low', 'none', 'reps', ARRAY['reps']::text[], 'kg', 0, 0, ARRAY['hip_thrust_machine']::text[], NULL, true, 1, 'Musculation (M1) — jamais tiré en metcon', true, 'fessiers', ARRAY['ischios']::text[], true, false, 'debutant', 'rpe', NULL, NULL, 3, 30, ARRAY['hypertrophie', 'force', 'endurance']::text[], '{"hypertrophie":[8,12],"force":[3,5],"endurance":[15,20]}'::jsonb, 0, 0, 8, 'reps', 2, 'hip_ext'),
  ('incline_push_up', 'Incline Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — mains sur box / banc / marche ; variante facile sans matériel', true, 'pecs', ARRAY['triceps', 'epaules_ant']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[8,12],"endurance":[15,20]}'::jsonb, 8, 6, 4, 'reps', 5, 'press_h'),
  ('wall_push_up', 'Wall Push-Ups', 'bodyweight', ARRAY['push_h']::text[], 'G', 'none', 'high', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY['wall']::text[], NULL, true, 1, 'Musculation — variante facile sans matériel', true, 'pecs', ARRAY['triceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 2, 2, 'reps', 5, 'press_h'),
  ('bird_dog', 'Bird Dog', 'bodyweight', ARRAY['core']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — reps alternées ; variante facile sans matériel', true, 'tronc', ARRAY['lombaires', 'fessiers']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 3, 5, ARRAY['endurance']::text[], '{"endurance":[10,16]}'::jsonb, 6, 6, 6, 'reps', 3, 'core_anti'),
  ('bodyweight_reverse_lunge', 'Reverse Lunge', 'bodyweight', ARRAY['hinge']::text[], 'G', 'none', 'none', 'reps', ARRAY['reps']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — sans charge ; reps alternées ; variante facile sans matériel', true, 'fessiers', ARRAY['quadriceps']::text[], true, false, 'debutant', 'bodyweight', NULL, NULL, 2, 10, ARRAY['hypertrophie', 'endurance']::text[], '{"hypertrophie":[10,16],"endurance":[16,24]}'::jsonb, 8, 6, 6, 'reps', 5, 'lunge'),
  ('squat_hold', 'Squat Hold', 'bodyweight', ARRAY['squat']::text[], 'G', 'none', 'none', 's', ARRAY['s']::text[], NULL, 0, 0, ARRAY[]::text[], NULL, true, 1, 'Musculation — unité secondes ; variante facile sans matériel', true, 'quadriceps', ARRAY['fessiers']::text[], false, false, 'debutant', 'bodyweight', NULL, NULL, 1, 5, ARRAY['endurance']::text[], '{"endurance":[15,20]}'::jsonb, 6, 6, 6, 's', 3, 'squat')
ON CONFLICT (id) DO UPDATE SET
  discipline_muscu = EXCLUDED.discipline_muscu, muscle_primary = EXCLUDED.muscle_primary,
  muscle_secondary = EXCLUDED.muscle_secondary, compound = EXCLUDED.compound, unilateral = EXCLUDED.unilateral,
  level_min = EXCLUDED.level_min, load_mode = EXCLUDED.load_mode, rm_reference = EXCLUDED.rm_reference,
  rm_factor = EXCLUDED.rm_factor, seconds_per_rep = EXCLUDED.seconds_per_rep, setup_s = EXCLUDED.setup_s,
  objectives = EXCLUDED.objectives, rep_ranges_muscu = EXCLUDED.rep_ranges_muscu,
  weight_bodyweight = EXCLUDED.weight_bodyweight, weight_box = EXCLUDED.weight_box, weight_gym = EXCLUDED.weight_gym,
  muscu_unit = EXCLUDED.muscu_unit, priority = EXCLUDED.priority, movement_group = EXCLUDED.movement_group,
  updated_at = now();
